### ISSUE TITLE
undefined method 'mailgun_settings=' for ActionMailer::Base:Class

### ISSUE THREAD

**Issue by elcactus** [mailgun/mailgun-ruby#104]
I'm consistently getting this error on server startup in an otherwise empty rails project with the following configuration:

```
ruby 2.3.4
rails 5.2.1
mailgun-ruby 1.1.6
```

**development.rb**
```
config.action_mailer.delivery_method = :mailgun
config.action_mailer.mailgun_settings = {
  api_key: "api key here",
  domain: "mailgun domain here"
}
```

**error message**
```
~/.rvm/gems/ruby-2.3.4/gems/actionmailer-5.1.1/lib/action_mailer/base.rb:580:in `method_missing': undefined method `mailgun_settings=' for ActionMailer::Base:Class (NoMethodError)
Did you mean?  sendmail_settings
```
I'm using `config.action_mailer.mailgun_settings=` as described in the gem's documentation. Not sure if this is a bug or a configuration issue.

**Comment by fadynaffa3** [comment]
Same with rails 4.2.8 and the minimum rails version needed is not mentioned in the documentation

**Comment by zorro2b** [comment]
Seems you need this Gem  also:
https://github.com/jorgemanrubia/mailgun_rails

**Comment by fadynaffa3** [comment]
@zorro2b This is a separate gem and it's not maintained by Mailgun themselves, but I have ended up using it alone without mailgun_ruby gem

**Comment by bramski** [comment]
Resolutions? Any?

**Comment by yoonwaiyan** [comment]
same error here, using Rails 4.2.5 with Ruby 2.3.1 . Removing require doesn't work for me.

**Comment by Benjamin-Dobell** [comment]
This is Rails bug, same underlying cause as #105. Fixed by pending PR https://github.com/rails/rails/pull/35419

**Comment by Benjamin-Dobell** [comment]
Should probably note there is an issue with this Gem as well, as it's causing `ActionMailer::Base` to autoload earlier than it ought to. Fixed in PR https://github.com/mailgun/mailgun-ruby/pull/162.

**Comment by Retttro** [comment]
Version 1.2.4 with the fix is published to rubygems. Closing.
https://github.com/mailgun/mailgun-ruby/releases/tag/v1.2.4
