### ISSUE TITLE
prevent sending multi-part mail if only html or text part is provided

### ISSUE THREAD

**Issue by HusseinMorsy** [mailgun/mailgun-ruby#107]
When a rails app sends only a text mail, then Railgun sends also the html part (converted from the text part).

The problem, is that all newlines are ignored, when the mail is view in an html capable mail client.

e.g. if the text part of a  mail  has two lines
```
first line
second line
````
then it  will be shown as one line  in a mail-client with html support.:

```
first line second line
````

this [code](https://github.com/mailgun/mailgun-ruby/blob/master/lib/railgun/mailer.rb#L138)  is the cause of the problem

**Comment by pirogoeth** [comment]
@HusseinMorsy https://github.com/mailgun/mailgun-ruby/pull/109

**Comment by Retttro** [comment]
Fixed in https://github.com/mailgun/mailgun-ruby/pull/132.
