### ISSUE TITLE
Unexpected token at 'Mailgun Magnificent API'

### ISSUE THREAD

**Issue by btkramm** [mailgun/mailgun-ruby#110]
I'm trying to send emails in background using delayed_job but for some reason raises *Unexpected token at 'Mailgun Magnificent API'* error. This only happens in production environment...

**Comment by pirogoeth** [comment]
@btkramm Can you give me some more information about your setup? Using Railgun or just the library portion? Version of Ruby? Possibly a usage snippet? Thanks!

**Comment by btkramm** [comment]
Ruby v2.4.0
Gem: `mailgun-ruby` v1.1.6

### Application config
```ruby
 config.active_job.queue_adapter = :delayed_job
```

### Development config
```ruby
  config.action_mailer.perform_caching = true
  config.action_mailer.perform_deliveries = true
  config.action_mailer.raise_delivery_errors = true
	config.action_mailer.delivery_method = :smtp

	config.action_mailer.smtp_settings = {
		address:        'smtp.gmail.com',
		port:           587,
    domain:         'gmail.com',
    user_name:      '',
    password:       '',
		authentication: :plain,
		enable_starttls_auto: true,
  }

	Mailgun.configure do |config|
		config.api_key = ''
	end

  config.action_mailer.mailgun_settings = {
    api_key: '',
    domain:  '',
  }
```
### Production config
```ruby
  config.action_mailer.default_url_options = { host: 'marcadorexacto.com' }
  config.action_mailer.perform_caching = true
  config.action_mailer.perform_deliveries = true
	config.action_mailer.delivery_method = :smtp

  config.action_mailer.smtp_settings = {
    address:        'smtp.gmail.com',
    port:           587,
    domain:         'gmail.com',
    user_name:      '',
    password:       '',
    authentication: :plain,
		enable_starttls_auto: true,
  }

	Mailgun.configure do |config|
		config.api_key = ''
	end

  config.action_mailer.mailgun_settings = {
    api_key: '',
    domain:  '',
  }
```

### Sending emails!
```ruby
  def remind
    users = User.all

    # RegExp validation
    users.select { |u| u.email =~ Devise.email_regexp }.each do |user|
      groups = Group.joins(:groups_users)
        .where(event: self.event, groups_users: { user: user, state: 0 }).to_a

      GroupMailer.reminder_email(user.email, self, groups).deliver_later

     # GroupMailer.delay.reminder_email(user.email, self, groups) also not working
    end
  end
```

### GroupMailer.reminder_email
```ruby
  def reminder_email receiver, match, groups
    @match, @groups = match, groups

    subject = t('emails.reminder.subject', match: @match.notification_repr)
    mail(to: receiver, subject: subject, delivery_method: :mailgun)
  end
```

**Comment by lleger** [comment]
I have also started to see this error. The stack trace makes it seem like it’s an error parsing JSON coming back in the response. My set up is similar to @btkramm’s. Using DelayedJob via ActiveJob. This error is in sending a BatchMessage with the gem. Regular emails are not impacted.

**Comment by lleger** [comment]
It seems like we forgot to set the Mailgun domain when initializing the BatchMessage object:

`message = Mailgun::BatchMessage.new(mailgun_client, ENV['MAILGUN_DOMAIN’])`

When we set that ENV var, it worked perfectly.

Might be a good opportunity for a better error message, but I don’t think we were experiencing a bug.

**Comment by iSarCasm** [comment]
Experienced this issue when MAILGUN_DOMAIN or MAILGUN_API_KEY was not given (nil). 
I would offer to add checks for this with good errors 'Missing Api key' etc.

**Comment by duartemvix** [comment]
Here's what I'm getting

![image](https://user-images.githubusercontent.com/19348306/50623108-c1a56b80-0ef9-11e9-8c62-c3765520ed15.png)

And I am calling it like this 
![image](https://user-images.githubusercontent.com/19348306/50623121-ea2d6580-0ef9-11e9-8976-a6007cf335fe.png)

**Comment by brentkearney** [comment]
I have a similar situation with Rails 5.2.2.1 and mailgun-ruby 1.1.6, but changing from .deliver_now to .deliver made no difference.

```
from SuckerPunch(urgent) in 1369.57ms: Mailgun::ParseError (767: unexpected token at 'Mailgun Magnificent API'):
/usr/local/rvm/gems/ruby-2.6.3/gems/mailgun-ruby-1.1.10/lib/mailgun/response.rb:32:in `rescue in to_h'
/usr/local/rvm/gems/ruby-2.6.3/gems/mailgun-ruby-1.1.10/lib/mailgun/response.rb:29:in `to_h'
/usr/local/rvm/gems/ruby-2.6.3/gems/mailgun-ruby-1.1.10/lib/railgun/mailer.rb:43:in `deliver!'
/usr/local/rvm/gems/ruby-2.6.3/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
/usr/local/rvm/gems/ruby-2.6.3/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
/usr/local/rvm/gems/ruby-2.6.3/gems/actionmailer-5.2.2.1/lib/action_mailer/base.rb:560:in `block in deliver_mail'
/usr/local/rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:168:in `block in instrument'
/usr/local/rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/usr/local/rvm/gems/ruby-2.6.3/gems/activesupport-5.2.2.1/lib/active_support/notifications.rb:168:in `instrument'
/usr/local/rvm/gems/ruby-2.6.3/gems/actionmailer-5.2.2.1/lib/action_mailer/base.rb:558:in `deliver_mail'
/usr/local/rvm/gems/ruby-2.6.3/gems/mail-2.7.1/lib/mail/message.rb:260:in `deliver'
/usr/local/rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/delegate.rb:83:in `method_missing'
/home/app/workshops/app/jobs/email_invitation_job.rb:26:in `perform'
```

It looks like the response.body from Mailgun is blowing up JSON.parse.

**Comment by urbanrotnik** [comment]
I am experiencing 
`Mailgun::ParseError (783: unexpected token at 'Mailgun Magnificent API'):` 
Only in production, works ok in development 

Using 
`mailgun-ruby (1.1.11)`
`rails 6.0.3`

**Comment by Retttro** [comment]
'Mailgun Magnificent API' returned as a response when the domain is invalid. Validation for the blank domain was added in 1.2.4. Closing the issue.
https://github.com/mailgun/mailgun-ruby/releases/tag/v1.2.4
