### ISSUE TITLE
Incorrect message_id after sending the message via rails mailer

### ISSUE THREAD

**Issue by aalbagarcia** [mailgun/mailgun-ruby#116]
Hi!

I have just installed the gem in one of our projects and it seems to work fine. However, I've noticed that I cannot get the Message-ID after sending the email. Following the documentation in the README:

```
  mailer = UserNotifier.welcome_email(current_user)
  mailer_response = mailer.deliver_now
  mailer_response.message_id => Returns the string "id" instead of the message id.
```
The message is sent through mailgun correctly, however the last line returns the string "id" instead of the message id (i was expecting something like <20170727122117.78172394....@mydomain.com>.

Looking at the code,  I could get the right Message-ID by changing just one line of code. Open the file [lib/railgun/mailer.rb](https://github.com/mailgun/mailgun-ruby/blob/master/lib/railgun/mailer.rb#L38) and change the deliver! function from:

```
    def deliver!(mail)
      mg_message = Railgun.transform_for_mailgun(mail)
      response = @mg_client.send_message(@domain, mg_message)
      if response.code == 200 then
        mg_id = response.body['id']  <<-----
        mail.message_id = mg_id
      end
      response
    end
``` 
to
```
    def deliver!(mail)
      mg_message = Railgun.transform_for_mailgun(mail)
      response = @mg_client.send_message(@domain, mg_message)
      if response.code == 200 then
        mg_id = response.to_h['id'] <<-----
        mail.message_id = mg_id
      end
      response
    end
``` 
and then I get the correct message id.

I'm using ruby 2.4.1 and the latest version of the gem (1.1.6). Any idea what I might be doing wrong?

**Comment by mosinski** [comment]
Same problem here:
Rails: `Rails 5.1.2`
Ruby: `ruby 2.4.1p111`

Your solution works!

**Comment by Retttro** [comment]
Fixed in https://github.com/mailgun/mailgun-ruby/pull/118 and published to rubygems. Closing.
