### ISSUE TITLE
Custom headers

### ISSUE THREAD

**Issue by crk2002** [mailgun/mailgun-ruby#117]
I'm using the mailgun-ruby gem to send messages through ActionMailer. I'm trying to attach custom headers so I can identify these messages in my web hooks, but the headers don't seem to go through. (When I check the mailgun logs, they aren't there, and they also aren't transmitted in the web hooks.) Here is an example of my method. Any ideas?

```ruby
  def invitation(invitation_id, reminder=false)
    @invitation = ProviderInvitation.find(invitation_id)
    headers 'X-Mailgun-Variables' => {provider_invitation_id: invitation_id.to_s, mail_type: "provider_invitation"}.to_json
    if reminder
      mail(to: @invitation.invited_email, from: "Contact <contact@xxxx.com>", subject: "Reminder: #{@invitation.sending_provider.name} invited you to join!")
      @invitation.update(reminder_sent: true)
    else
      mail(to: @invitation.invited_email, from: "Contact <contact@xxxx.com>", subject: "#{@invitation.sending_provider.name} invited you to join!")
    end
  end
```

**Comment by crk2002** [comment]
So far it seems the only solution is to send using SMTP.

**Comment by benhart** [comment]
I also ran into this (but also for sending options such as tracking).

I found this is the mailgun-ruby source (https://github.com/mailgun/mailgun-ruby/blob/master/lib/railgun/mailer.rb):
```ruby
  def transform_for_mailgun(mail)
    message = build_message_object(mail)

    # v:* attributes (variables)
    mail.mailgun_variables.try(:each) do |k, v|
      message["v:#{k}"] = v
    end

    # o:* attributes (options)
    mail.mailgun_options.try(:each) do |k, v|
      message["o:#{k}"] = v
    end

    # h:* attributes (headers)
    mail.mailgun_headers.try(:each) do |k, v|
      message["h:#{k}"] = v
    end

    # recipient variables
    message['recipient-variables'] = mail.mailgun_recipient_variables.to_json if mail.mailgun_recipient_variables

    # reject blank values
    message.delete_if do |k, v|
      v.nil? or (v.respond_to?(:empty) and v.empty?)
    end

    return message
  end
```

It wasn't clear to me at all how to set those attributes on the mail object given my mailers (I found the relationship between an action mailer and mail pretty obscure).

So I wrote this extension that mapped from my headers to set those attributes. It allows me to switch between using SMTP and mailgun sending, just using custom MIME headers.


```ruby
module RailgunExtensions

  HEADER_OPTIONS_MAP = {'X-Mailgun-Track' => 'tracking', 'X-Mailgun-Track-Clicks' => 'tracking-clicks', 'X-Mailgun-Track-Opens' => 'tracking-opens', 'X-Mailgun-Tag' => 'tag'}

  def transform_for_mailgun(mail)
    mail.mailgun_options ||= {}
    mail.header_fields.each do |field|
      option = HEADER_OPTIONS_MAP[field.name]
      mail.mailgun_options[option] = field.value if option
      if field.name == 'X-Mailgun-Variables' && field.value
        mail.mailgun_variables = JSON.parse(field.value)
      end
    end
    super(mail)
  end
end

Railgun.singleton_class.prepend RailgunExtensions
```

Using this I just set the headers as usual, either: `default 'X-Mailgun-Track' => 'no'` for the mail, or within individual methods `headers 'X-Mailgun-Variables' => { 'client_guid' => user.client_guid }.to_json`.

I have no doubt it could be better written, and there's likely a way simpler solution, but this worked for me. (That said I'm still trying to decide whether to stick with this, or just revert to using SMTP.)

**Comment by pirogoeth** [comment]
Hey all,
The "official" way to send custom headers on a message is by adding your headers to a hash like you see [here](https://github.com/pirogoeth/railgun-sample/blob/master/app/controllers/users_controller.rb#L105). 

The same goes for options and variables. 

Let me know if you have any more questions. Thanks!

**Comment by holman** [comment]
Cheers, @pirogoeth. That pointed me to the right direction. :sparkles:

I think it'd be neat if this gem could use the proper ActionMailer `headers()` method and pass the headers to the `mailgun_headers` method here. Or, at least for a stopgap, put a note in the README about this (even after a search through the source this didn't pop out at me today).

Basically was a little odd to go from a "Railsy" thing in an ActionMailer class like:

```ruby
def an_email
  mail(to: ...)
  headers(dope_headers)
end
```

to have to operate on the `mail` object:

```ruby
def an_email
  message = mail(to: ...)
  message.mailgun_headers = dope_headers
end
```

But it's a relatively minor thing anyway. :)

**Comment by pirogoeth** [comment]
@holman Glad it got you going in the right direction!

I'll see if I can make some changes and get the more "Railsy" way of using `headers()` working :)

**Comment by benhart** [comment]
Yeah, thanks @pirogoeth , seems a better approach! Look forward to seeing what you come up with.

**Comment by pirogoeth** [comment]
@benhart @holman @crk2002 I've opened a [PR](https://github.com/mailgun/mailgun-ruby/pull/133) adding support for `headers()` calls, along with docs and tests for Railgun. Y'all mind reviewing it and providing some feedback?

**Comment by Retttro** [comment]
Fixed in https://github.com/mailgun/mailgun-ruby/pull/133 and published to rubygems. Closing.
