### ISSUE TITLE
Batch sending adds everyone to the To field

### ISSUE THREAD

**Issue by davidbalbert** [mailgun/mailgun-ruby#12]
# The bug

When you batch send a message with the mailgun-ruby gem, using the `Mailgun::BatchMessage` class, every recipient sees themselves and all the other recipients in the To field.
# How to reproduce

I used this code. I'm using rails, so Action Mailer is responsible for rendering the message:

``` ruby
mail = FooMailer.a_batch_email(recipients)

client = Mailgun::Client.new(ENV["MAILGUN_API_KEY"])
batch_message = Mailgun::BatchMessage.new(client, "mail.community.hackerschool.com")

batch_message.set_from_address(mail.from.first)
batch_message.set_subject(mail.subject)
batch_message.set_text_body(mail.body.to_s)

mail.to.each do |recipient|
  batch_message.add_recipient(:to, recipient)
end

batch_message.finalize
```

The only difference from https://github.com/mailgun/mailgun-ruby/blob/master/Messages.md is that I'm not passing in any recipient variables, but this should be fine because `BatchMessage#add_recipient` creates default recipient variables if  nothing is passed as a third argument.
# What I expect

Each recipient in `mail.to` should receive a copy of the email with only their email address in the To field. 
# What actually happens.

Each recipient in `mail.to` receives an email with everyone in `mail.to` in the To field.

Using the API directly by following the instructions in the [docs](http://documentation.mailgun.com/user_manual.html#batch-sending) works as expected.

**Comment by pirogoeth** [comment]
Has this been solved?

**Comment by 9mm** [comment]
Is this really not solved? This makes the entire feature useless. It looks like this gem isn't even maintained, come on guys. Thats what I am paying for. I send 5mm emails and I need to build all this shit by hand because THREE year old crazy issues never get fixed

**Comment by pirogoeth** [comment]
Using this code, it appears that batch mailing with recipient variables works as expected without adding everyone in the `To` field.

```
batch_message = Mailgun::BatchMessage.new(c, domain)

batch_message.set_from_address("batch@example.org")
batch_message.set_subject("Batch Mail Test")
batch_message.set_text_body("This is a test of the batch mailer with recipient variables.")

to.each do |recipient|
  batch_message.add_recipient(:to, recipient)
end

batch_message.finalize
```
