### ISSUE TITLE
Better Exceptions

### ISSUE THREAD

**Issue by ctrlaltdylan** [mailgun/mailgun-ruby#120]
I appreciate the pastebin-esque method of debugging emails, but it's cumbersome and doesn't help debug with the _exact_ error you have.

Why not have custom exceptions that the library understands and get thrown with the approriate HTTP response?

400 is used as a blanket error - can we at least parse the HTTP error messages from the API and throw a more helpful exception?

`Mailgun::Api::InvalidRequest message="Please specify a message body with your request"` 

The actual exception format needs to be thought through, but this would be a huge improvement over the pastebin.

**Comment by Retttro** [comment]
Fixed in mailgun-ruby version 1.2.5. Closing.
