### ISSUE TITLE
Mailer.mailgun_client incorrect return value

### ISSUE THREAD

**Issue by mccarths** [mailgun/mailgun-ruby#125]
In https://github.com/mailgun/mailgun-ruby/blob/master/lib/railgun/mailer.rb#L50 it should be returning `@mg_client` instead of `@mg_obj`.

**Comment by pirogoeth** [comment]
@mccarths I'm pushing out a fix for this in the 1.1.9 release, thanks for the report!

**Comment by bramski** [comment]
Is this still an issue?

**Comment by Retttro** [comment]
Fixed in https://github.com/mailgun/mailgun-ruby/pull/153 and published to rubygems. Closing.
