### ISSUE TITLE
Mailgun does not accept From header with display name

### ISSUE THREAD

**Issue by youngbrioche** [mailgun/mailgun-ruby#126]
Feeding Mailgun in Rails (Railgun) with a complex MIME sender string via ActionMailer's `from` setting leads to 

`Mailgun::CommunicationError: 400 Bad Request: 'from' parameter is not a valid address. please check documentation (Error)`

Only plain email addresses (without sender display names encoded) work.

Steps to reproduce:

```ruby
config.action_mailer.delivery_method = :mailgun

class ApplicationMailer < ActionMailer::Base
  default from: "First Last <first.last@aol.com>"
end
```

**Comment by zeefarmer** [comment]
Cannot reproduce
