### ISSUE TITLE
Set o:tracking when track_clicks/opens is called

### ISSUE THREAD

**Issue by scottrobertson** [mailgun/mailgun-ruby#129]
If tracking is disabled in domain settings, calling `track_clicks/opens` will not override those settings unless you also pass `o:tracking` too.

For example, the following overrides the setting:

```
msg.send(:set_multi_simple, 'o:tracking', 'yes')
```

This should be set automatically if either `track_clicks` or `track_opens` is called in my opinion. If not, the docs need to be updated to make this very clear.

**Comment by pirogoeth** [comment]
@scottrobertson I agree. I will attempt to get a fix in for this soon.

**Comment by Retttro** [comment]
Fixed in version 1.2.5. Closing.
