### ISSUE TITLE
Cannot send pure plain/text (or plain/html) mail

### ISSUE THREAD

**Issue by fursich** [mailgun/mailgun-ruby#130]
### what happens

With Mailgun-ruby (specifically speaking railgun), `Content-Type` is always set as `multipart/alternatives`, ignoring ActionMailer's default settings.

It occures even when you have only text (or html) templates in views folder with headers correctly specified as `plain/text`, which is unexpected behavior comparing with the way [ActionMailer is defined](http://guides.rubyonrails.org/action_mailer_basics.html).

It might be a corner case thing - in most cases your users have no problems to have the both html and text emails sent out altogether, but at least it would be great at least we can handle this situation, for instance, with config settings.

### why it matters

I encountered a problem when I was trying to send out text-only mails for certain old mobile devices.

When you prepare only html templates, the html is copied as text as well and sent out as multipart email. As all the html tags remain on the text as it originally was, certain text mail clients will get a message with full of html tags.

On the other hand, if you prepare only text templates, it seems that the text version is copied as html version and the email is sent out as multipart, which also is a headache when text-only old mobile devices has to be considered (which unfortunately is my case)

1) you cannot create text-only email at all

2) the html is a mere copy of the original text template, using html mail client you will see no line break is applied.

3) on the other hand, when you prepare html format only, with text-only clients you will get a text mail with full of html tags on, because the original html is being copied as text as it is.

### how to reproduce

Assume we have a `user` from User model and SampleMailer:

```ruby
# app/mailers/sample_mailer

class SampleMailer < ActionMailer::Base

  def hello(user)
    @user = user
    mail(from: 'xxx@example.com' ,to: user.email, subject: "Hello") { |format| format.text }
  end
end
```

and its template..

```ruby
# app/views/sample_mailer/hello.text.erb

<%= "Hello #{@user.nickname}" %>
This is a test mail.
```

(needless to say, all emails are fake here)

When you create an email on rails console, you will get

```ruby
pry(main)> mail = SampleMailer.hello(user)
[INFO ]   Rendering sample_mailer/hello.text.erb
[INFO ]   Rendered sample_mailer/hello.text.erb (1.8ms)
=> #<Mail::Message:70193536029860, Multipart: false, Headers: <From: xxxxx@example.com>, <To: yyyyy@example.com>, <Subject: Hello>, <Mime-Version: 1.0>, <Content-Type: text/plain>>
```

Here you can see:

1) only text mail is rendered
2) the Content-Type is now `text/plain`, with Multipart option set as false

Now you dispatch.

```ruby
pry(main)> mail.deliver_now

=> #<Mail::Message:70193536029860, Multipart: false, Headers: <Date: Wed, 15 Nov 2017 12:44:24 +0900>, <From: xxxxx@example.com>, <To: yyyyy@example.com>, <Message-ID: id>, <Subject: Hello>, <Mime-Version: 1.0>, <Content-Type: text/plain>, <Content-Transfer-Encoding: 7bit>>
```

Again, The log explains that content-type is `text/plain` as expected.

However when you actually open the received mail and check its source, you will get:

```
Content-Type: multipart/alternative; boundary="9027d1d9743c4e5fb464da103fb78ff6"

--9027d1d9743c4e5fb464da103fb78ff6
Content-Transfer-Encoding: 7bit
Content-Type: text/plain; charset="ascii"
Mime-Version: 1.0


Hello World

This is a test mail.

--9027d1d9743c4e5fb464da103fb78ff6
Content-Transfer-Encoding: 7bit
Content-Type: text/html; charset="ascii"
Mime-Version: 1.0


Hello World

This is a test mail.

--9027d1d9743c4e5fb464da103fb78ff6--
```

### source code

After digging the codes for a while, I found out that railgun overwrites html mail into text mail (or vise versa) unless the both templates are present (meaning, when multipart option is set `false`).

(see [here](https://github.com/mailgun/mailgun-ruby/blob/9e6fbb7cf48eb38aa739b85ad568b12e2724a537/lib/railgun/mailer.rb#L141) and [here](https://github.com/mailgun/mailgun-ruby/blob/9e6fbb7cf48eb38aa739b85ad568b12e2724a537/lib/railgun/mailer.rb#L155))

Not sure if it's intended or not, but I would be happy to PR if a preferred approach is specified (i.e. do we switch the default behavior depending on config settings, or do we follow the default ActionMailer behaviors?)
Any advices?

(by the way thanks as always for maintaining this useful gem!)

**Comment by pirogoeth** [comment]
@fursich Hello! Thank you for the extremely in-depth report! It would be extremely helpful if you could submit a PR for this issue.

> Not sure if it's intended or not, but I would be happy to PR if a preferred approach is specified (i.e. do we switch the default behavior depending on config settings, or do we follow the default ActionMailer behaviors?)

 I believe it would be best to follow the default ActionMailer behaviours.

**Comment by fursich** [comment]
Hi @pirogoeth, thanks for swift feedback!

> I believe it would be best to follow the default ActionMailer behaviours.

That's making sense to me, let me submit a PR accordingly.

**Comment by pirogoeth** [comment]
I will close this issue out when I cut the 1.1.9 release. :)

**Comment by fursich** [comment]
Great. Thanks @pirogoeth !

**Comment by tclaus** [comment]
Need to close this?

**Comment by fursich** [comment]
@tclaus  
Oh yes, apparently the current version is already marked as 1.1.9.
Thanks for reminding!

**Comment by tclaus** [comment]
There are a bunch of issues still unclosed? 
😉
