### ISSUE TITLE
Tracking API

### ISSUE THREAD

**Issue by eebs** [mailgun/mailgun-ruby#131]
Hello,

I noticed the Tracking endpoints are not available in the `Mailgun::Domains` class. Would it be possible to add those endpoints? Would you accept a PR adding those endpoints?

Thanks!

**Comment by pirogoeth** [comment]
@eebs It is certainly possible to add those and we would absolutely accept a PR with those changes!

**Comment by eebs** [comment]
Great. I'll see if I can find some time to open a PR.
