### ISSUE TITLE
Mailgun issue with attachment with custom extensions

### ISSUE THREAD

**Issue by tanya355** [mailgun/mailgun-ruby#136]
I've an attachment that is uploaded by end-user which is sent to mailgun-ruby as tempfile. 

**add_attachment()** method seems to need the file path to be specified with the extension. If the path to the file is specified without the extension or its an unusual extension (_.lsgfx_) then the mail is received with a corrupted attachment twice the size of the one being sent with content-type as text/plain

`Content-Disposition: attachment; filename="black-red-gloss.lsgfx"
Content-Type: text/plain; charset="utf-8"; name="black-red-gloss.lsgfx"`

Is there a way around this like an attachment content-type field I can set to `application/octet-stream` or something?.
Or am I doing something wrong. I've googled and nothing particularly helpful has come up.
mailgun-ruby 1.1.8, ruby 2.2.7p470

**Comment by Retttro** [comment]
Version v1.2.3 with the fix is released. Closing.
https://github.com/mailgun/mailgun-ruby/pull/216
