### ISSUE TITLE
Easy rails integration

### ISSUE THREAD

**Issue by Paxa** [mailgun/mailgun-ruby#14]
Would be nice to see easy rails integration
Something like this: https://github.com/Paxa/mailgun-rails

Any plans to implement it?

**Comment by pirogoeth** [comment]
I know this issue has been open for a bit -- I'm going to try to make Rails integration with this library a little less painful.

**Comment by brauliobo** [comment]
it is quite weird as the rails support is stated on the README, would be really useful to have this support!

**Comment by brauliobo** [comment]
Both https://github.com/code-mancers/rails-mailgun and https://github.com/jorgemanrubia/mailgun_rails are returning `400 bad request`! rails support needed :stuck_out_tongue:

**Comment by pirogoeth** [comment]
@brauliobo I will work on it today :)

**Comment by brauliobo** [comment]
btw, https://github.com/code-mancers/rails-mailgun is buggy with html emails

**Comment by pirogoeth** [comment]
ah okay, thanks! i'll check that out.

**Comment by pirogoeth** [comment]
@brauliobo I have a working preliminary implementation of Rails support in mailgun-ruby (Railgun) which you can try out here if you want: https://github.com/mailgun/mailgun-ruby/pull/72

Please feel free to provide feedback! I will be continuing to improve it soon.
