### ISSUE TITLE
parse_address always formats it as '' <user@host.domain> even when neither full_name, nor first, nor last variables are passed

### ISSUE THREAD

**Issue by primijos** [mailgun/mailgun-ruby#141]
When using add_recipient or reply_to methods, even when the variables hash does not contain any of full_name, first or last, the message gets composed with addresses in the form ('' <user@email>) (that is, with an empty full name).

Looks like the method parse_address (called from the methods cited above) uses defined? to check if a variable full_name has been defined by some previous logic:

https://github.com/mailgun/mailgun-ruby/blob/32f9d729321ffda475ab69c3ce310ba42ff7cb17/lib/mailgun/messages/message_builder.rb#L392

but the fact is that ruby defines it (as local-variable) even when none of the if-elsif branches previous to this check is taken, so defined?full_name is true, but it is empty when used, resulting in ''

Probably it should be initialized as nil before the if-elsif block, and checked against full_name.nil? instead of using defined?

**Comment by Retttro** [comment]
Version v1.2.3 with the fix is released. Closing.
https://github.com/mailgun/mailgun-ruby/pull/222
