### ISSUE TITLE
Why can you only use the public api key for email validation

### ISSUE THREAD

**Issue by uri** [mailgun/mailgun-ruby#145]
>Mailgun provides two types of API keys that can be used to access the email validation API:
>
>Public Validation Key - Suitable for use in client-side web applications, such as through the jQuery plugin.
>Private API Key - To be used in backend applications where there is not a risk of key exposure.
>
> **Mailgun recommends that you use the private key.**

Currently it seems that [Address#initialize](https://github.com/mailgun/mailgun-ruby/blob/master/lib/mailgun/address.rb#L11) only works with the public key.

**Comment by mgrishko** [comment]
We are switching to using v4 in the next release.
