### ISSUE TITLE
Unsubscribe API returns Invalid JSON error

### ISSUE THREAD

**Issue by AJMiller** [mailgun/mailgun-ruby#150]
Versions:
> Ruby: 2.5.1p57
  Rails: 5.2
  Mailgun-Ruby: 1.1.9

Code sample:
```ruby
mg_client = Mailgun::Client.new(MAILGUN_API_KEY)
unsubscribe_client = mg_client.suppressions(MAILGUN_DOMAIN)

users = ["myemail@example.com", "youremail@example.com"]
unsubscribe_body = users.map do |user_email|
  {
    address: user_email,
    tags: ["my_tag"]
  }
end
response, addt_responses = unsubscribe_client.create_unsubscribes unsubscribe_body
```

Expected Response: `2 addresses have been added to the unsubscribes table`

Actual Response: `Invalid JSON`

Initial Code Review: It appears that [this line](https://github.com/mailgun/mailgun-ruby/blob/master/lib/mailgun/suppressions.rb#L161) is expecting all hash values to be strings. When passing in tags, however, [the documentation](https://documentation.mailgun.com/en/latest/api-suppressions.html#add-multiple-unsubscribes) states that an array is required. If I construct the RestClient request myself, with a tag array, the request is successful:

```ruby
unsubscribe_client = RestClient::Resource.new(
  "https://api.mailgun.net/v3/#{MAILGUN_DOMAIN}/unsubscribes",
  "api",
  MAILGUN_API_KEY
)

users = ["myemail@example.com", "youremail@example.com"]
unsubscribe_body = users.map do |user_email|
  {
    address: user_email,
    tags: ["my_tag"]
  }
end

response = unsubscribe_client.post(
  unsubscribe_body.to_json,
  content_type: "application/json"
)
```

**Comment by caleb** [comment]
Thanks for this! I was trying to figure out what I was doing wrong. I saw mention on the Mailgun documentation that the language APIs don't support multiple tags so the first thing I tried was using a single string tag with the keys `tags` and with `tag`, and of course neither works.

I'm guessing that just removing the string requirement would work.

**Comment by LukasBarry** [comment]
Any word on a fix for this? Just ran into the same problem. Works great for adding bounces and complaints, but when i went to run unsubscribes i got the same error

**Comment by Retttro** [comment]
Version v1.2.3 with the fix is released. Closing.
@LukasBarry Thanks for the PR with the fix. It is in master now.
