### ISSUE TITLE
Domains in EU Region not working

### ISSUE THREAD

**Issue by mastermoo** [mailgun/mailgun-ruby#151]
Its not possible to connect to a domain, that uses the new EU region.

Looking at the code, it only works with US regions.
https://github.com/mailgun/mailgun-ruby/blob/0189a5b8042ed330e15d792fe5e039d2a937095b/lib/mailgun/client.rb#L14
The above line needs to be configurable. I believe for EU regions, the api host must be `api.eu.mailgun.net`

**Comment by MichalBryxi** [comment]
For rails/ActionMailer this settings works:

```
 config.action_mailer.mailgun_settings = {
    api_key: 'api-myapikey',
    api_host: 'api.eu.mailgun.net',
    domain: 'mydomain.com',
  }
```

**Comment by SirRawlins** [comment]
@mastermoo looking to use this myself today, but looking at the source you've linked, it seems that the host is already configurable, the line you link is an initialize argument on the client.

```ruby
Mailgun::Client.new('xxxx', 'api.eu.mailgun.net')
```

Does that not do what you'd expect?

**Comment by MichalBryxi** [comment]
Cool. Did not know about that option. Would be probably a good idea to put that in documentation. Can't find it in the repo readme.

**Comment by mastermoo** [comment]
@SirRawlins you are right, I should have looked more carefully.
