### ISSUE TITLE
Options to run mailgun via Proxy

### ISSUE THREAD

**Issue by empeje** [mailgun/mailgun-ruby#152]
I need a use case where my k8s where I deploy the application doesn't have direct internet connection except via proxy. And it is so bad that `mailgun-ruby` uses `rest-client` where it is only support global proxy setting if we use `Resource` class. Any idea to implement it?

**Comment by Retttro** [comment]
Feature added in version 1.2.5. Closing.

**Comment by empeje** [comment]
THanks @Retttro 🎉
