### ISSUE TITLE
Reply-to header is being duplicated

### ISSUE THREAD

**Issue by brandonweiss** [mailgun/mailgun-ruby#157]
Version `1.1.11` has a bug where two reply-to headers are sent to Mailgun, one is `h:reply-to` and the other is `h:Reply-To`.

This causes the email that is sent to have two reply-to headers, which when someone replies to that email in their email client, pre-populates the `to` field with two identical entries, causing two emails to be sent.

The bug seems to have been introduced in 265efffd51209b0170a3225bbe945b649643465a. I rolled back to `1.1.10` and saw only one reply-to header being sent.

**Comment by pirogoeth** [comment]
@brandonweiss mind checking if #158 fixes your issue?

**Comment by benhart** [comment]
@pirogoeth, I had this same issue with duplicate reply-to's. 

I actually also noticed from our logs and complaints that some providers were rejecting the mail outright as a result - for example had `Server response: 550 Messages should have one or no Reply-To headers, not 2.`

I pointed my apps to #158 (branch sjohn/no-duplicate-headers), and can confirm that this fixes the issue. I didn't test too thoroughly, but did check that user variables and tags also made their way up.

Is there anything I can help with to get this merged and released?

**Comment by benhart** [comment]
Great, thanks @pirogoeth. I took a look at #158 . Unfortunately, I don't know enough about the internals to give too informed an opinion.

But one comment is that if there are multiple headers with differently cased names, the approach means that the last value in the each loop will be the one that remains. In our case with duplicates that's completely fine, but if they were different I'm not sure...

I suppose trying to eliminate the duplicate headers in the first place would be best, but I haven't really followed how they come about to begin with.

So ya, overall, it seems very sane :)

**Comment by pirogoeth** [comment]
Okay, thank you @benhart! You're definitely right about differently-cased headers being a problem. As far as I knew, headers were case-insensitive, but `Mail::Message` seems to encode them separately...
```
irb(main):001:0> require 'mail'
=> true
irb(main):002:0> msg = Mail::Message.new
=> #<Mail::Message:70203334478840, Multipart: false, Headers: >
irb(main):003:0> msg.headers({'x-header': 'foo', 'X-Header': 'bar'})
=> {:"x-header"=>"foo", :"X-Header"=>"bar"}
irb(main):004:0> msg.header.encoded
=> "x-header: foo\r\nX-Header: bar\r\n"
```

I'm not sure to proceed, so I'll look into the SMTP/MIME spec and talk to my team over the next few days and see how to move forward!

**Comment by benhart** [comment]
Okay, thanks @pirogoeth. Look forward to hearing any solution you find!

**Comment by brandonweiss** [comment]
@pirogoeth Thanks for fixing this!

Regarding the specifics of the fix, if the values of the headers are identical you could collapse them, but if the values are different I’m not sure it’s necessarily a good idea to arbitrarily pick one of them. That could lead to some very confusing and difficult to debug outcomes. If it were me, I would raise an exception and fail to send if duplicate headers are found. It seems highly unlikely that if duplicate headers are found that the sender is going to get the outcome they’re expecting*.

*I don’t actually know much about the email spec, so this is predicated on the assumption that there isn’t some scenario where you actually do need to repeat the same header multiple times.

P.S. Unrelated, but do you… happen to be a Megatokyo fan? 😄

**Comment by pirogoeth** [comment]
@brandonweiss I 100% agree, I think raising an exception on duplicates (even if we take case-insensitivity into account) is the correct thing to do. From my peek through [RFC-822](https://tools.ietf.org/html/rfc822), [Section 3.4.7](https://tools.ietf.org/html/rfc822#section-3.4.7)  says that header names are case-insensitive. Ultimately, I would have expected `Mail::Header` to collapse headers where the names were equal, but `¯\_(ツ)_/¯`.

Anyway, yes, I am a Megatokyo fan! Haven't done a read-through of the series in ages though. Guess that means you're a fan as well? 😄

**Comment by brandonweiss** [comment]
@pirogoeth Hah, I used to read it ages ago, back in high school. At some point my tastes changed and I stopped reading it, but it was one of my favorites for many years. ❤️

**Comment by pirogoeth** [comment]
@brandonweiss thoughts? https://github.com/mailgun/mailgun-ruby/pull/158/commits/0f538d0d172a1b1f9b6c681ee1c28bb8857b90f4

**Comment by wilpar** [comment]
Folks, new mailgun user here, just ran into this issue.  I try to avoid moving to non-standard branches wherever possible (as I always forget to remove them!!), so while I wait for this to be merged/resolved, is there any potential harm (other than it looking funny in my mail app) to be faced by having duplicate headers?
Thanks!

**Comment by benhart** [comment]
@wilpar we found that some obscure providers were actually rejecting the mail altogether, pretty much a worst case scenario. I noted this above, we saw in our logs `Server response: 550 Messages should have one or no Reply-To headers, not 2`. 

We've been pointed to this branch in our Gemfile ever since, with no issues: 
`gem 'mailgun-ruby', :git => 'https://github.com/mailgun/mailgun-ruby', :branch => 'sjohn/no-duplicate-headers'`.

**Comment by wilpar** [comment]
@benhart Thanks!

**Comment by bulinutza** [comment]
Is there any update on this issue? It's been open since April and the bug is still occurring :-(

**Comment by chrisnankervis** [comment]
We discovered this last week and are now running #158 (0f538d0d172a1b1f9b6c681ee1c28bb8857b90f4) in production without any issues.

A big thanks to @pirogoeth for putting that together 🙌 

I'd really like to see it merged as well, considering deliverability is affected as @benhart has pointed out.

**Comment by chrisnankervis** [comment]
I've just opened a ticket via Mailgun support, so hopefully this issue is resolved soon.

**Comment by pirogoeth** [comment]
Sorry folks, #158 is merged and tagged! I appreciate all the feedback and testing you've all provided!
