### ISSUE TITLE
Error performing ActionMailer::DeliveryJob FrozenError (can't modify frozen Array)

### ISSUE THREAD

**Issue by derosm2** [mailgun/mailgun-ruby#159]
After updating to the latest release 1.1.11, we started to get the following error when we attempt to send any email:

```
can't modify frozen Array
/usr/local/bundle/gems/mailgun-ruby-1.1.11/lib/railgun/mailer.rb:122:in `delete_if'
/usr/local/bundle/gems/mailgun-ruby-1.1.11/lib/railgun/mailer.rb:122:in `block in transform_for_mailgun'
/usr/local/bundle/gems/mailgun-ruby-1.1.11/lib/railgun/mailer.rb:118:in `delete_if'
/usr/local/bundle/gems/mailgun-ruby-1.1.11/lib/railgun/mailer.rb:118:in `transform_for_mailgun'
/usr/local/bundle/gems/mailgun-ruby-1.1.11/lib/railgun/mailer.rb:43:in `deliver!'
```

Rails 5.2.2
Ruby 2.5.1

We are able to run 1.1.10 without any issues.

**Comment by derosm2** [comment]
Looks like the issue is because we freeze our tags (per [Rubocop](https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Style/MutableConstant)):
```rb
class SomeMailer < ApplicationMailer
  TAGS = %w[some-tag].freeze
end
```

which then gets used like so:
```rb
mail.mailgun_options ||= { "tag" => self.class::TAGS }
```

**Comment by Retttro** [comment]
Version v1.2.3 with the fix is released. Closing.
https://github.com/mailgun/mailgun-ruby/pull/221
