### ISSUE TITLE
how to send from different domains?

### ISSUE THREAD

**Issue by krtschmr** [mailgun/mailgun-ruby#161]
DOCS of mailgun are saying: 

> For SMTP, you have an SMTP username and password for each domain you have registered at Mailgun. To send mail from a particular domain, just use the appropriate credentials. For the API, the domain is one of the parameters in the URI.

yet our config is quite static

```
 config.action_mailer.mailgun_settings = {
    api_key: 'api-myapikey',
    domain: 'mydomain.com',
  }
```

If you have a multidomain platform, say forum hosting or whatever, how to change the domain dynamically based on _who_ is sending the email?

**Comment by tatums** [comment]
Perhaps there's a better (more official) way to do this, but here is how I've achieved this in a Rails 4 app. 

First, add a new delivery_method to ActionMailer.

```ruby
  # Add a new delivery_method
  ActionMailer::Base.add_delivery_method :second_domain, Railgun::Mailer

  # Add the second_domain keys
  config.action_mailer.second_domain = {
    api_key: 'your-api-key',
    domain:  "your-domain.com"
  }
```

Next, You need to specify which domain when sending your mail.

```ruby
mailer = UserMailer.confirmation("user@example.com")
mailer.second_domain.delivery_method = :second_domain
mailer.deliver_later
```

**Comment by krtschmr** [comment]
actually i checked and it seems that we can do it dynamically from the `UserMailer`, just change the domain accordingly (and change it back)

**Comment by leonelgalan** [comment]
@krtschmr, could you share with us (other users) how to change it dynamically from the Mailer. Once you do, maybe close this issue.

**Comment by krtschmr** [comment]
well, hijacking SpreeCommerce

```

Spree::BaseMailer.class_eval do

  def mail(headers = {}, &block)
    ensure_default_action_mailer_url_host
    if store = @shipment.try(:order).try(:store) || @order.try(:store)
      setup_mailgun_domain(store) if Rails.env.production?
    end
    super
  end

  private

  def setup_mailgun_domain(store)
    if store.mailgun_domain.present?
      Rails.application.config.action_mailer.mailgun_settings[:domain] = store.mailgun_domain
    end
  end

end

```

basically, you can call `Rails.application.config.action_mailer.mailgun_settings[:domain]`from anywhere you want and it's working

**Comment by joshm1204** [comment]
I tried using an interceptor to change the domain dynamically, but it does not seem to work.  My interceptor does run, and the config does change, but the old value is used when the email sends. Does anyone know why?

## lib/server_mail_interceptor

```
class ServerMailInterceptor
  def self.delivering_email(message)
      Rails.application.config.action_mailer.mailgun_settings[:domain] = 'emails.mydomain.com'
  end
end
```
## environment/development.rb
```
 ActionMailer::Base.register_interceptor(ServerMailInterceptor) # Intercepts emails
```

**Comment by xab3r** [comment]
The other option could be setting domain in a mailer using `delivery_method_options` param:

```ruby
class MyMailer < ApplicationMailer
  def notify(options)
    mail options.merge(
      delivery_method_options: { domain: "second.domain" }
    )
  end
end
```

**Comment by darmenise** [comment]
This is important, we need a simple and reliable way to do this. Where is the Mailgun team, please?

**Comment by krtschmr** [comment]
> This is important, we need a simple and reliable way to do this. Where is the Mailgun team, please?

there are 2.5 working solutions in this thread. all are reliable. do they work for you?

**Comment by darmenise** [comment]
Hello @krtschmr, thank you for your concern! we need to set the sending domain the mail method. I tried @xab3r's solution, and it seemed to be working until I checked the MIME type of the sent email:

```
Content-Transfer-Encoding: quoted-printable
Received: by luna.mailgun.net with HTTP; Mon, 18 Jan 2021 10:03:00 +0000
Sender: info=correct.domain@wrong.domain
```
Also Mailgun log are not showing the email sent under the right domain, they do show it under the wrong one.

Ideally, we should be able to do configure multiple domains like this:

```ruby
  ActionMailer::Base.delivery_method = :mailgun
  ActionMailer::Base.mailgun_settings = [
    { api_key: ENV['MAILGUN_API_KEY'], domain: ENV['MAILGUN_DOMAIN_1'], api_host: 'api.eu.mailgun.net' },
    { api_key: ENV['MAILGUN_API_KEY'], domain: ENV['MAILGUN_DOMAIN_1'], api_host: 'api.eu.mailgun.net' }
  ]
```

And then select them from the `mail` method like this:

```
@mailgun_response = mail(from: from,
                               reply_to: reply_to,
                               to: @whitelisted_emails,
                               cc: cc,
                               bcc: bcc,
                               domain: domain, # <= HERE
                               subject: subject,
                               'X-Mailgun-Tag': tag)
```

Anyway, I think that the Mailgun team should provide the **official** solution for this problem since (1) it's a paid service and (2) their docs tell us that it is possible to send from multiple domains.

**Comment by darmenise** [comment]
Eureka, finally we patched this gem (like this)[https://github.com/Corsidia/mailgun-ruby/pull/2/files], and now we're able to simply call:

```
class YourMailer < ApplicationMailer
  def sample_email_with_custom_domain(message)
    mail(to: message.email, subject: message.subject, domain: 'your.custom.domain')
  end
end
```

Adding new custom domains is now as easy as adding them to Mailgun, and then setting them from `mail[:domain]`. 
No need to change the config because the config domain is used as the default one.

**Comment by oliwoodsuk** [comment]
I'd also be interested in this being merged. Good work Darmenise. 
I'm surprised it wasn't already an option to be honest. Any B2B app that sends email on behalf of customers would surely be getting this requested often.

**Comment by Retttro** [comment]
Option to specify the domain added in version 1.2.5 and released https://github.com/mailgun/mailgun-ruby/pull/242. Closing.

**Comment by DanielKakona1** [comment]
This issue should be reopened. All the provided solutions are not working.
