### ISSUE TITLE
Allow specifying of sender email

### ISSUE THREAD

**Issue by mtohmaz** [mailgun/mailgun-ruby#164]
When using this gem instead of Rail's mailer, whenever we send an email it will set the sender as `postmaster@e.medsender.com`, which would cause emails to automatically be filtered into the spam folder in certain inboxes.

I compared the mailgun logs to see what the difference was between the mailgun client and the rail's mailer was. Here's what I found:

Mailgun client:
It would set the sender in the envelope header as `postmaster@e.medsender.com`.

Ruby mailer:
It would set the sender in the envelope to whatever was set as `from:` email.

Is there a way I can modify the behavior of the mailgun client to match the ruby mailer?

**Comment by Retttro** [comment]
@mtohmaz Based on the name of the issue: you can specify default `from` email in `application_mailer.rb ` or pass a parameter `from: 'from@example.com` to the #mail method. Or do you want to use this exact email?

**Comment by Retttro** [comment]
@mtohmaz Mailgun does not allow to specify sender specifically, only the from. We set the sender programmatically based on certain parameters. Closing the issue.
