### ISSUE TITLE
MessageBuilder#track_clicks usage is unclear

### ISSUE THREAD

**Issue by aprescott** [mailgun/mailgun-ruby#165]
(Using Mailgun 1.1.11.)

This may just be an issue of documentation, but it looks like [`MessageBuilder#track_clicks`](https://github.com/mailgun/mailgun-ruby/blob/v1.1.11/lib/mailgun/messages/message_builder.rb#L209-L215) has unclear usage. It accepts `track_clicks(false)`, but in my testing that doesn't seem to have an effect.

[Mailgun docs](https://documentation.mailgun.com/en/latest/user_manual.html) suggest that `o:tracking` can be set with `o:tracking=False`, but it isn't clear to me if `set_multi_simple("o:tracking-clicks", ["no"])` (which is how `track_clicks(false)` currently works) is supported.

I've worked around this in an application by switching to the header method, [for which the Mailgun docs](https://documentation.mailgun.com/en/latest/user_manual.html#passing-sending-options) are a little clearer: `header("X-Mailgun-Track-Clicks", "no")`.

**Comment by Retttro** [comment]
Version v1.2.3 with the fix is released. Closing.
https://github.com/mailgun/mailgun-ruby/pull/219
