### ISSUE TITLE
Allow Mailgun template feature

### ISSUE THREAD

**Issue by pedrofs** [mailgun/mailgun-ruby#166]
Although we can set template variables to get passed to the client:

```
mail(...).tap do |message|
  message.mailgun_headers = {'X-Mailgun-Variables': {foo: 'bar'}}
end
```

There is no way to tell to the message to use a template id/name.

My idea is to have it something like that:

```
mail(...).tap do |message|
  message.mailgun_template = {name: 'template_name', variables: {foo: 'bar'}}
end
```

Thoughts?

**Comment by facundofarias** [comment]
Hello! Any update about this?

**Comment by Mbuckley0** [comment]
Is there any update on this as it would be a nice feature to have.

**Comment by Retttro** [comment]
Feature added in maigun-ruby gem version 1.2.5. Closing.
