### ISSUE TITLE
Trouble with "count" parameter

### ISSUE THREAD

**Issue by nneal** [mailgun/mailgun-ruby#17]
I am trying to get counts of certain events. 

I am using the following 

``` ruby
client.get("mg.mydomain.com/events", { count: 'true', event: 'clicked' }) 
```

However, I'm getting the error:

```
Mailgun::CommunicationError: {
  "message": "Unknown parameter: count=['yes']"
}
```

I tried a few other variations, but could not get anything to work. I am referencing the docs here: http://documentation.mailgun.com/api-campaigns.html#events which I believe should allow for the `count` param that I'm using. If I remove "count", the request will go through, but I get the actual events rather than the count. I want the counts to do some stats on my end.

Thank you!

Neal

**Comment by pirogoeth** [comment]
Was this solved?

**Comment by pirogoeth** [comment]
This has been stale for a while, so I'm gonna close this issue. Feel free to re-open if this is still a problem.
