### ISSUE TITLE
Strict versioning for rest-client

### ISSUE THREAD

**Issue by DannyBen** [mailgun/mailgun-ruby#176]
Is there a reason for the strict dependency versioning?

The gemspec requires this:

```ruby
spec.add_dependency 'rest-client', '~> 2.0.2'
```

which will cause any `bundle update` in a an application that has a newer `rest-client` to simply not upgrade the mailgun gem.

The only way for me to get the latest `mailgun-ruby` was to do this in my Gemfile:

```ruby
gem 'mailgun-ruby', '> 1.1.10'
```

which caused a downgrade of my rest-client:

```
Using rest-client 2.0.2 (was 2.1.0)
Using mailgun-ruby 1.2.0 (was 1.1.10)
```

Is there a reason the dependency restriction can't be just:

```ruby
spec.add_dependency 'rest-client', '~> 2.0'
```

**Comment by bgmat** [comment]
Just to add to @DannyBen post,  version 1.1.10 has rest-client (~> 2.0) ... so, it works with rest-client 2.1.0, which makes it even stranger why newer versions were limited to rest-client 2.0.2

**Comment by n-rodriguez** [comment]
Hi there! Any news?
