### ISSUE TITLE
using an erb template in the message_params

### ISSUE THREAD

**Issue by birthdaycorp** [mailgun/mailgun-ruby#178]
Love this gem! Is it possible to use an erb template in the `message_params`? If so - how? 
```
mg_client = Mailgun::Client.new ENV['MAILGUN_API_KEY']
 message_params = {
 from: "Admin <admin@site.com>",
 to: record.email,
 subject: "Your account has been approved",
 html: ##my email template is at users/mailer, and i'm unsure about how to make this work.
}
```
[This](https://github.com/mailgun/mailgun-ruby/blob/master/docs/Messages.md) is some help. Presumably, I would do something like:

```
mg_client = Mailgun::Client.new ENV['MAILGUN_API_KEY']
mb_obj = Mailgun::MessageBuilder.new
mb_obj.set_html_body(??) #insert erb template here?
```

**Comment by cfaguayo** [comment]
@birthdaycorp did you find a way to resolve it? Thanks!

**Comment by birthdaycorp** [comment]
@cfaguayo yes, turns out I can continue to use ActionMailer's default `mail()` syntax for sending emails. I had assumed that setting `config.action_mailer.delivery_method = :mailgun` in **environment.rb** would  make me reliant on the gem's MessageBuilder syntax, but I was wrong.
