### ISSUE TITLE
cannot use europe region 

### ISSUE THREAD

**Issue by alphamarket** [mailgun/mailgun-ruby#179]
You didn't specify the `api_host` in this your [config file](https://github.com/mailgun/mailgun-ruby/blob/master/lib/mailgun.rb) so we cannot configure when Europe region for our domain?

**It's always the US region!**

**Comment by leewaa** [comment]
Just discovered this also! I had first thought it was to do with a domain configuration error. A quick curl confirmed my domain is working and I can send emails with MailGun. Just not with the gem as it is not possible to set the `BASE_URL`, only the domain can be set.

**Comment by leewaa** [comment]
@alphamarket actually I discovered it is posssible. Just undocumented.

Check the the code here https://github.com/mailgun/mailgun-ruby/blob/9ad7112a7d41e613539476ecadd07736a2bd315d/lib/railgun/mailer.rb#L32

So in your config use:
```ruby
config.action_mailer.mailgun_settings = {
  api_key: <your_key>,
  domain: <your_domain>,
  api_host: 'api.eu.mailgun.net'   
}
```

**Comment by alphamarket** [comment]
```ruby
config.action_mailer.mailgun_settings = {
  api_key: <your_key>,
  domain: <your_domain>,
  api_host: 'api.eu.mailgun.net'   
}
```
Did you test this? because if I remember correctly I have read your code and tried this before I submit the issue. This did not work.

**Comment by leewaa** [comment]
Yeah, this is how I got it working for me.

**Comment by johannesschirrmeister** [comment]
Thanks, this solved it for me. Would be lovely if this were added to the Readme.

**Comment by leewaa** [comment]
There are some pull requests open adding documentation about this.

**Comment by IvanSelivanov** [comment]
What is mailgun_host [here](https://github.com/mailgun/mailgun-ruby/blob/master/lib/mailgun.rb)? I don't see that it is used anywhere. Wasn't it meant to be used for setting api_host?

**Comment by kirqe** [comment]
This should be marked in all caps and bold instead of just a tiny comment

**Comment by Retttro** [comment]
[Readme.md](http://readme.md/) mentions the EU region. Closing.
