### ISSUE TITLE
Headers being deleted when sent via Rails

### ISSUE THREAD

**Issue by dkam** [mailgun/mailgun-ruby#180]
Adding headers ( List-Unsubscribe and X-MyTesto ) when sending via rails are visible in the console, but don't appear in the received email. 

When emailing like this: 
```ruby
  mail(to: "#{user.name} <#{user.email}>", subject: 'Test subject','List-Unsubscribe' => '<mailto:unsub@mydomain.com.au>', 'X-MyTesto' => 'Goodo' ) do |format|
      format.html { render layout: 'user_mailer' }
      format.text
    end.mailgun_options = { tag: tag }
```

I can see this in the console:

```shell
Content-Transfer-Encoding: 7bit
List-Unsubscribe: <mailto:unsub@mydomain.com.au>
X-MyTesto: Goodo
```

But they don't appear in my received email.

**Comment by ojundt** [comment]
You'll need version 1.2.0+ for custom headers to be picked up by the mailer. This was added in #133.

**Comment by dkam** [comment]
Thanks.  Are you able to release a new gem with that functionality?

**Comment by ojundt** [comment]
Unfortunately I'm not but you're not the only one asking. See #193.

**Comment by Retttro** [comment]
Fixed in https://github.com/mailgun/mailgun-ruby/pull/133 and published to rubygems, closing.
