### ISSUE TITLE
Not working with latest version of mailgun-ruby gem

### ISSUE THREAD

**Issue by dewey** [mailgun/mailgun-ruby#182]
Hey,

I'm trying to get this to work for a few hours now (`gem 'mailgun-ruby', '~>1.2.0'`) and I think I've tried everything. I still can't get it to work and I'm a bit confused what goes wrong. Doing it via curl works instantly and I receive the email (with the same credentials and hostnames as used with `mailgun-ruby`).

Working curl command:

```
curl -X "POST" "https://api.eu.mailgun.net/v3/mail.mydomain.com/messages" \
     -H 'Content-Type: multipart/form-data; charset=utf-8;  \
     -u 'api:my-api-key' \
     -F "from=Excited User <hello@mydomain.com>" \
     -F "to=testing@myotherdomain.com" \
     -F "subject=Hello" \
     -F "text=Test message!"
```

responds with a :
```
{
  "id": "<redactedmessageid@mail.mydomain.com>",
  "message": "Queued. Thank you."
}
```

Test script:
```
require 'mailgun'

# First, instantiate the Mailgun Client with your API key
mg_client = Mailgun::Client.new('my-api-key', 'api.eu.mailgun.net')

# Define your message parameters
message_params = {:from    => 'hello@mydomain.com',
                  :to      => 'testing@myotherdomain.com',
                  :subject => 'The Ruby SDK is awesome!',
                  :text    => 'It is really easy to send a message!'}

# Send your message through the client
a = mg_client.send_message "https://api.eu.mailgun.net/v3/mail.mydomain.com", message_params
puts a.inspect
```

Response:

```
#<Mailgun::Response:0x00007fe11d2615a0 @body="Mailgun Magnificent API", @code=200>
```

One thing I noticed was that curl is sending it as a multi-part form, that's also what the Go library does but in this `mailgun-ruby` library I can't find the place where it's sending the request as a form payload, it seems to just do a normal POST request with a JSON body?

**What I tried**

I now tried to use the other gem and it worked out of the box, so I suspect that something is broken in the current state of the library.

```
require 'mailgunner'

message_params = {:from    => 'hello@mydomain.com',
                  :to      => 'testing@myotherdomain.com',
                  :subject => 'The Ruby SDK is awesome!',
                  :text    => 'It is really easy to send a message!'}

Mailgunner.configure do |config|
  config.domain = 'mail.mydomain.com'
  config.api_key = 'my-api-key'
  config.api_host = 'api.eu.mailgun.net'
end

mailgun = Mailgunner::Client.new

s = mailgun.send_message(message_params)
ap s
```

When I look into this library it's submitting it as a form payload too so my guess is that the `mailgun-ruby` library is sending it in a normal POST body which isn't accepted by the Mailgun API (any more?). Maybe it was only tested with the SMTP backend?

How `mailgunner` sends the request:
```
    def post(path, attributes = ATTRIBUTES)
      transmit(Net::HTTP::Post.new(path)) { |message| message.set_form_data(attributes) }
    end
```

Grateful for any pointers, thanks!

**Comment by zeefarmer** [comment]
+ mg_client.send_message "mail.mydomain.com", message_param
- mg_client.send_message "https://api.eu.mailgun.net/v3/mail.mydomain.com", message_params
