### ISSUE TITLE
Mailgun could have thousands of new customers thanks to Tecnativa module to integrate Odoo with Mailgun

### ISSUE THREAD

**Issue by rafaelbn** [mailgun/mailgun-ruby#189]
Hi Mailgun, @horkhe , @obukhov-sergey

Maybe you could take a look that [Odoo ERP / CRM Open Source](https://github.com/Odoo/odoo) has [4 million users around the world](https://www.odoo.com/page/about-us) and the most in USA.

Tecnativa has developed 6 years ago a module to integrate Odoo with Mailgun's Webservices.

https://github.com/OCA/social/tree/8.0/mail_tracking_mailgun
https://github.com/OCA/social/tree/9.0/mail_tracking_mailgun
https://github.com/OCA/social/tree/10.0/mail_tracking_mailgun
https://github.com/OCA/social/tree/11.0/mail_tracking_mailgun
https://github.com/OCA/social/tree/12.0/mail_tracking_mailgun

This module is Open Source and Free: https://www.odoo.com/apps/modules/12.0/mail_tracking_mailgun/

Let say, Mailgun could sell to thousand of new customers thanks to this module.

Regards

**Comment by Yenthe666** [comment]
And 13.0: https://github.com/OCA/social/tree/13.0/mail_tracking_mailgun
