### ISSUE TITLE
Publish to Rubygems

### ISSUE THREAD

**Issue by n-rodriguez** [mailgun/mailgun-ruby#193]
Hi there!

Can you please upload releases 1.2.1 and 1.2.2 on https://rubygems.org/gems/mailgun-ruby ?

Thank you!

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by arenoir** [comment]
Please publish as this is preventing me from updating some of our internal gems.  Specifically this commit 504850ef532edc9e17208516b67e992e8c252821

**Comment by n-rodriguez** [comment]
Hi there! Any news?

**Comment by c2ofh** [comment]
Don't know why we're paying money to mailgun...

**Comment by ojundt** [comment]
> Hello Oliver,
> 
> Thank you for contacting Mailgun support. 
> 
> We are aware that our customer accesible code implementations and SDKs are in need of some attention and we are working on addressing this internally, but we have no current ETA on when any updates would be available. However, we do recommend submitting this feedback to our Product Feature/Feedback site [1]. Our Product team regularly reviews user feedback to inform our product roadmap. As a request obtains more feedback, the higher the chances will be that the team selects the idea for development and prioritizes its implementation. 
> 
> Please let us know if you have any additional questions.
> 
> Regards,
> Levi | Mailgun Support
> 
> [1] - https://feedback.mailgun.com/

**Comment by n-rodriguez** [comment]
> Our Product team regularly reviews user feedback to inform our product roadmap. As a request obtains more feedback, the higher the chances will be that the team selects the idea for development and prioritizes its implementation.

WTF? It's a shame. We're not talking about features but about releases... There's nothing new here...

**Comment by n-rodriguez** [comment]
I hate this kind of marketing bullshit answers...

**Comment by c2ofh** [comment]
I also dropped a ticket. The answer was following:

> Thank you for reaching out to Mailgun support.
> 
> At this moment we do not have an ETA on updating the ruby SDK, but I will reach out to our team to confirm this. Once I have more information I will update this ticket for you.

**Comment by n-rodriguez** [comment]
> I also dropped a ticket. The answer was following:

Yes... they are still deciding if a new release is a bug or a feature...

**Comment by c2ofh** [comment]
The ticket was updated. Expectations are high :D

> We are getting this over to the appropriate member of our team for further assistance. We will update this ticket as soon as we can.

**Comment by n-rodriguez** [comment]
Hi there! Any news? This is fantastic that we have no official answers for Mailgun team. Do you need developers? I can send you a quote if you like.

**Comment by BKSpurgeon** [comment]
For those of you reading wanting the latest releases, rather than using ruby gems as the source, you could simply use:

```ruby
gem 'mailgun-ruby', git: 'https://github.com/mailgun/mailgun-ruby.git', tag: 'v1.2.2'
```

**Comment by BKSpurgeon** [comment]
Github actions allows for the easy automation of publishing to ruby gems, making it even easier: https://github.com/actions/starter-workflows/blob/8c0ca1f934427262760a2492caead41a84f964c4/ci/gem-push.yml

**Comment by jacobjlevine** [comment]
Adding my +1 for this.

**Comment by cmfarmer** [comment]
Hi all, very sorry for the lack of updates here. Not only will we be pushing the releases here in Github to https://rubygems.org/gems/mailgun-ruby, but we're also working on a new release, which I expect to be ready to go in Q1 2021.

**Comment by n-rodriguez** [comment]
>  which I expect to be ready to go in Q1 2021.

yeah... I bet for Q2 or Q3...

**Comment by n-rodriguez** [comment]
almost a  year for this : https://github.com/mailgun/mailgun-ruby/commit/d21d6c385ad834e5eaa5ba8cc4a2cca0fc7ddec7

**Comment by benkoshy** [comment]
@n-rodriguez - we can use github to pull that commit into your project rather than wait till it's punished as a ruby gem ---- we've been waiting a long time ---as you've said --- management seem indifferent to allocating the resources to do it
