### ISSUE TITLE
Not working for Rails 5

### ISSUE THREAD

**Issue by pawlarius** [mailgun/mailgun-ruby#196]
Hi all, I tried to follow [this part of Readme](https://github.com/mailgun/mailgun-ruby#rails) for Rails integration. 

After couple of hours, it seems nothing work. Tried debugging in the mailgun-ruby code directly, and can't find anything useful, only got `#<RestClient::Unauthorized: 401 Unauthorized>` and `Mailgun::CommunicationError (401 Unauthorized: Forbidden)`.

Even tried putting the user:password directly as url in the code, like `https://api:[MY_API_KEY]@api.mailgun.net/v3/[MY_DOMAIN]/messages`, also got the same errors.

I have tried using 1.1.11 and latest commit with git ref '504850e'. Both result in the same errors.
I'm using Rails 5 & Ruby 2.5.0. Did anyone had success with integrating this library with Rails app?

My credentials are correct because i've tried this with curl and it works fine.

**Comment by Talha5** [comment]
@pawlarius Im having the same issue, did you get to solve it?
