### ISSUE TITLE
Release version 1.2.2 to rubygems.org

### ISSUE THREAD

**Issue by achadee** [mailgun/mailgun-ruby#198]
Hi running into a lot of rest-client conflicts and would really love 1.2.2 to be released,

using docker has issues with calling repo tags, plus it looks loads cleaner :^)

eg.
```
gem 'mailgun-ruby', git: 'https://github.com/mailgun/mailgun-ruby', tag: 'v1.2.2'
```

**Comment by n-rodriguez** [comment]
See https://github.com/mailgun/mailgun-ruby/issues/193

**Comment by n-rodriguez** [comment]
Closed by https://github.com/mailgun/mailgun-ruby/pull/223

**Comment by n-rodriguez** [comment]
ping @Retttro

**Comment by Retttro** [comment]
Version 1.2.3 is released to RubyGems. Closing.
