### ISSUE TITLE
Inline Attachment with Action Mailer

### ISSUE THREAD

**Issue by c2ofh** [mailgun/mailgun-ruby#199]
I was sending emails to mailgun with smtp. I had no issues.
Now I changed to API with the gem.

Some emails are containing images, which should be attached inline to the email.
When I was sending the mails with SMTP it works fine. Now the image is just broken.
In manipulate the email html before sending with Nokogiri::HTML:

```ruby
name = media.send(type).blob.filename.to_s
attachments[name] = File.read(media.local_path(size, type))
node.attributes['src'].value = "cid:#{attachments[name].cid}"
```

The image is attached, but not shown. 
![image](https://user-images.githubusercontent.com/10913793/84528776-92934c00-ace0-11ea-80f2-d870f30187bf.png)

**Comment by Retttro** [comment]
@c2ofh Embedding images should be done using :inline attribute:

client = Mailgun::Client.new(...)
client.send_message("your.domain",
  { 
    # ...
    body_html: "Embedding <img src='cid:image.jpg'>",
    inline: File.new("image.jpg")
  }
)
Closing this issue. If you have any problems with that approach, please feel free to reopen the issue.
