### ISSUE TITLE
Custom variables must be JSON object

### ISSUE THREAD

**Issue by miduddin** [mailgun/mailgun-ruby#200]
Attaching custom variables using `Mailgun::MessageBuilder#variable` enforces the variable to be in JSON object format (raises error otherwise), is this behavior intended? Because the  HTTP API seems to be fine with any string (just like the example on [manual page](https://documentation.mailgun.com/en/latest/user_manual.html#attaching-data-to-messages)).

I'm trying to work with webhooks from Mailgun, and there's one extra step to parse the variables because they came in JSON serialized string.

**Comment by miduddin** [comment]
I've created the PR above just in case.

**Comment by Retttro** [comment]
Version 1.2.4 with the fix is released. Closing.
https://github.com/mailgun/mailgun-ruby/releases/tag/v1.2.4
