### ISSUE TITLE
Mailgun is deleting calendar/ics mime

### ISSUE THREAD

**Issue by alexroitman** [mailgun/mailgun-ruby#203]
Im trying to send an invite with mailgun-ruby gem.
The mail has HTML content, and the ics invite:
```ruby
      attachments['invite.ics'] = {
        mime_type: 'application/ics',
        content: ics
      }
```
The attachment send correctly but apparently, when i send the invitation to outlook i need to send it with the attachment, a mime string with this headers
```ruby
      email.add_part(Mail::Part.new do
        content_type "text/calendar;charset=UTF-8;method=REQUEST"
        content_transfer_encoding '7bit'
        body ics
      end)
```
so that, outlook can parse and show the RSVP invite.
The problem appears when mailgun send the mail.
On my console i see(perfectly):

```
----==_mimepart_5f526d8581c9b_1193f3fe0a15ce4ac245ce
Content-Type: text/calendar;
 charset=utf-8;
 method=REQUEST
Content-Transfer-Encoding: 7bit

BEGIN:VCALENDAR
PRODID:-//MY LLC//MY Calendar//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:REQUEST
BEGIN:VEVENT
DTSTART:20200730T000000Z
DURATION:PT1H
RRULE:FREQ=WEEKLY;COUNT=15
EXDATE:
DTSTAMP:20200723T210404Z
ORGANIZER;CN=Nulinga:mailto:info@test.com
UID:fe0baa5c-6c5a-4f85-bbb8-0
......
```
But when i see the sended mail disappears.

**Comment by CrazybutSolid** [comment]
did you find a way to make it work?

**Comment by alexroitman** [comment]
Change our implementation to send through SMTP

**Comment by Retttro** [comment]
Fixed in https://github.com/mailgun/mailgun-ruby/pull/133 and published to rubygems closing.
