### ISSUE TITLE
Test mode?

### ISSUE THREAD

**Issue by michaelrkn** [mailgun/mailgun-ruby#24]
Hey there! Really loving the new Mailgun gem - thanks for the good work.

One thing that I'm running into in my testing is that it's annoying to stub Mailgun out every time I hit an action in my app that sends an email. It would be awesome to be able to do something like

```
Mailgun.enable_test_mode!
```

in my `spec_helper.rb` that would then cause all the client to not actually make requests to Mailgun. 

I was thinking about working on this and opening a pull request, but wanted to see your folks' thoughts on it in case you have other suggestions or a better approach before I go down that path.

Thanks!

**Comment by Linuus** [comment]
@macmm Any updates? :innocent:

**Comment by pirogoeth** [comment]
@michaelrkn @Linuus If you still want this feature, I could give it a go and submit a patch in a couple days. Are you still interested in this feature?

**Comment by michaelrkn** [comment]
@pirogoeth I'm not personally using the gem currently, but I bet the project I was working on would use the feature if it were available!

**Comment by pirogoeth** [comment]
@michaelrkn Thanks for the feedback! I'll work on it when I get some time. :)

**Comment by Linuus** [comment]
I'm not on a project that uses this library anymore either. The next time I am though, this feature would be very nice to have!

**Comment by sixfeetover** [comment]
I would definitely be interested in this - currently my tests actually do send emails. Sometimes that's helpful to verify the output, but often it would be nice to be able to run tests in real time (e.g. with guard) without actually sending the emails all the time.

**Comment by pirogoeth** [comment]
I'm going to start this out with just blocking email sending during test mode and we can move forward to other chunks of the API that we would want to stub out :)

**Comment by pirogoeth** [comment]
Fulfilled! #66
