### ISSUE TITLE
Using mailgun templates and passing variables?

### ISSUE THREAD

**Issue by conorbr** [mailgun/mailgun-ruby#244]
Is there any documentation for setting up my mailer to make use of the templates I have stored on Mailgun and passing variables to have them sent through the service.

Currently I can only seem to get the results I want by pasting the template html into a view and using embedded ruby.

Happy to add to the project readme :)

**Comment by joshmcarthur** [comment]
Hey @conorbr, I had the same question. I found the mailer specs useful for showing how this works: https://github.com/mailgun/mailgun-ruby/blob/68e0c6f1863b7ca07904cf1b1efaec1498c64511/spec/unit/railgun/mailer_spec.rb, in particular:

* [Sending a message with a template specified](https://github.com/mailgun/mailgun-ruby/blob/68e0c6f1863b7ca07904cf1b1efaec1498c64511/spec/unit/railgun/mailer_spec.rb#L317)
* [Sending a message with attached data](https://github.com/mailgun/mailgun-ruby/blob/68e0c6f1863b7ca07904cf1b1efaec1498c64511/spec/unit/railgun/mailer_spec.rb#L124)

I've got to get on with actually integrating Mailgun into my project now, so I won't update the README, but hopefully someone else might, and if not then at least these links are here to help the next person searching for how to do this :-)

**Comment by joshmcarthur** [comment]
I did find the block passed to `mail` was important to have ActionMailer not try and load the template from app/views though.

**Comment by joshmcarthur** [comment]
Adding `body: ""` to the `mail` params works by tricking ActionMailer into thinking we don't want a Rails template rendered.

Here's the example that's working for me:

```
class ApplicationMailer < ActionMailer::Base
  default from: Rails.application.secrets.mail_from
  layout "mailer"

  def test
    message = mail(to: "test@example.com", subject: "Test", template: "test", body: "")
    message.mailgun_variables = { "user" => { id: 1, name: "test" } }

    message
  end
end
```

**Comment by btoone** [comment]
@joshmcarthur Thanks so much for posting your info! You saved me a ton of time.

For anyone implementing this, I can confirm what @joshmcarthur posted works to send a Mailgun template. You have to be using v1.2.5. If you don't pass `body` to `#mail` then the lib will complain that you're not using a block.  I tested adding a block and using `format.text {render body: ""}` which works but just providing the `body` as an arg like @joshmcarthur did is nicer.

The only other hangup I had was that the specs show the use of `message.mailgun_template_variables = ...` but I couldn't get that to work. Had to use `mailgun_variables` exactly as @joshmcarthur has in his example and it works.

For ref, here is the commit where support for templates was added https://github.com/mailgun/mailgun-ruby/pull/242/commits/31b1801efd257d9f61b63cc23e75b917f565298c

**Comment by MichalBryxi** [comment]
Saved my day. If you follow the `body` and `mailgun_variables` trick from @joshmcarthur it should work.

The issue has been opened for nearly year and a half. Too long for Mailgun to let the users step on this rake 😢

**Comment by Retttro** [comment]
A templates documentation was added in the release https://github.com/mailgun/mailgun-ruby/releases/tag/v1.2.7.
https://github.com/mailgun/mailgun-ruby/pull/267
Closing the issue.
