### ISSUE TITLE
Multipart messages through ActionView

### ISSUE THREAD

**Issue by thed000d** [mailgun/mailgun-ruby#249]
I am using version 1.2.5 as the action_mailer delivery method with the https://github.com/simukappu/activity_notification gem. 

I have two mail templates: `won.html.erb` and `won.ics.erb`. When sending with SMTP through Mailgun, both parts of the message are successfully sent. When sending with the https://github.com/readysteady/mailgunner gem, both parts of the message are successfully sent. When sending mailgun-ruby, only the html part of the message is sent.

**Comment by Retttro** [comment]
@thed000d Issue does not reproduce. Does it still reproduce for you? If yes, could you please provide more details? Thanks!

**Comment by zeefarmer** [comment]
Cannot reproduce
