### ISSUE TITLE
Check for ActionMailer instead of Rails

### ISSUE THREAD

**Issue by joeosburn** [mailgun/mailgun-ruby#254]
This https://github.com/mailgun/mailgun-ruby/blob/master/lib/mailgun-ruby.rb#L2 is not a good enough way to check for the presence of `ActionMailer`.

Our app is not a Rails app and does not support ActionMailer, but `Rails` is defined because we use at least one spun-off Rails gem: https://github.com/rails/rails-html-sanitizer/blob/master/lib/rails-html-sanitizer.rb#L6

Ideally, then, the above line would be replaced with something like this:

```
require 'railgun' if defined?(ActionMailer)
```

**Comment by Retttro** [comment]
Version 1.2.6 with the fix is released now. Closing.
https://github.com/mailgun/mailgun-ruby/releases/tag/v1.2.6
