### ISSUE TITLE
TypeError: no implicit conversion of nil into String

### ISSUE THREAD

**Issue by proton** [mailgun/mailgun-ruby#256]
We've got an error during an execution of
https://github.com/mailgun/mailgun-ruby/blob/master/lib/mailgun/exceptions/exceptions.rb#L58

I guess you need to add
```
rescue NoMethodError
  api_message = "Unknown API error"
rescue
  api_message = $!.message
end
```
or

```
rescue NoMethodError
  api_message = "Unknown API error"
rescue
  raise
end
```

to https://github.com/mailgun/mailgun-ruby/blob/master/lib/mailgun/exceptions/exceptions.rb#L54

**Comment by Retttro** [comment]
Version 1.2.6 with the fix is released now. Closing.
https://github.com/mailgun/mailgun-ruby/releases/tag/v1.2.6
