### ISSUE TITLE
Use multiple domains with different sending keys

### ISSUE THREAD

**Issue by DanielKakona1** [mailgun/mailgun-ruby#258]
I'm working with `mailgun-ruby` but
I have an issue with sending emails from different domains.

I saw there was an issue already opened for that and it was closed but all the provided solutions are not working for me. (https://github.com/mailgun/mailgun-ruby/issues/161)

I have something like this already in my  config file
```
 config.action_mailer.mailgun_settings = {
    api_key: 'api-myapikey',
    domain: 'mydomain.com',
  }
```

Now If I want to override this setting with another domain, how to change the domain dynamically based on who is sending the email?

Like if user B is now sending the email change the domain and the API key.
```
 config.action_mailer.mailgun_settings = {
    api_key: 'userB-apikey',
    domain: 'userB-domain',
  }
  ```

**Comment by krtschmr** [comment]
the linked thread did close with a PR which included a commit

https://github.com/mailgun/mailgun-ruby/pull/242/files#diff-58dfc2edb1d6b2b8b29513f8835de2f9ee084becd5e31484958dbe8b3f4a8b5cR50-R54

have you seen that?

**Comment by DanielKakona1** [comment]
Yeah, I did but this doesn't work with a domain sending key.  I just can't pass the domain like this:
```
mail(to: recipient_email, subject: subject, domain: seconddomain)
```
This gives me an error about the `invalid domain or API Key`. 

So I tried overriding the config on the mailer with something like this:

```
      if (userB) 
        Rails.application.config.action_mailer.delivery_method = :mailgun
        Rails.application.config.action_mailer.mailgun_settings = {
          api_key: second_domain_api_key,
          domain: second_domain,
        }
      end
      
``` 
however, this doesn't override the domain set on the config file.

**Comment by benhart** [comment]
I think the problem here is that we're using domain sending keys, not the single account api key. Is there a reasonably simple way to use multiple domains with different sending keys?

**Comment by Retttro** [comment]
A method to set different API key was introduced in https://github.com/mailgun/mailgun-ruby/releases/tag/v1.2.7.
https://github.com/mailgun/mailgun-ruby/pull/263/files#diff-448492d7de7ea726559e7a2616d096c7622de209064ac3ad14898e8fce4d18a8R49
Closing the issue.
