### ISSUE TITLE
Error handling if queue is full

### ISSUE THREAD

**Issue by tillvollmer** [mailgun/mailgun-ruby#26]
Right now if the mailgun queue is full (500k emails) you will get an error back.
Error handling should cover this, by either retrying after waiting some seconds or issue an error that says "you may retry in a couple of seconds". 
This may even happen on a single email (without batch).

When you use the API for ActionMailer this is even worse as emails are just not sent.

**Comment by pirogoeth** [comment]
I've talked with the team and we've decided that this is out of scope for the library. I will make sure that the library throws a distinguishable `QueueFullException` when this happens. 

I will also make sure that the API for ActionMailer can handle a full queue when I get around to implementing it. Thanks for the report :)
