### ISSUE TITLE
Is there a way to handle different recipient variables with same email

### ISSUE THREAD

**Issue by viveki2it** [mailgun/mailgun-ruby#266]
- I have one scenario to use the different recipient variables with same email and need to send the email twice using the sending batch 
- When I use the recipient variables using the `add_recipient` method with same email and different variables. It is merging the values with latest one. 
i.e : `{:first_name=>"Junko", :last_name=>"Collier", :username=>"Junko.Collier", :database_id=>"reilloC.oknuJ", :time_zone=>"Eastern Time (US & Canada)", :email=>"testdec27@mailinator.com", :network_name=>"Demo Network", :group_name=>nil, :user_id=>nil, :contact_id=>221682, :preferred=>false, :with_quiet_hour=>false, :quiet_time=>nil, :first_name_0=>"Junko", :last_name_0=>"Collier", :email_0=>"esta@mailinator.com"} `
`{:first_name=>"Rodrick", :last_name=>"Reichel", :username=>"Rodrick.Reichel", :database_id=>"lehcieR.kcirdoR", :time_zone=>"Eastern Time (US & Canada)", :email=>"testdec27@mailinator.com", :network_name=>"Demo Network", :group_name=>nil, :user_id=>nil, :contact_id=>221684, :preferred=>false, :with_quiet_hour=>false, :quiet_time=>nil, :first_name_0=>"Rodrick", :last_name_0=>"Reichel", :email_0=>"dora@mailinator.com"}`
- when we get the response merged with above ones and latest one added to the variables :
`@recipient_variables={ "esta@mailinator.com"=>{:first_name=>"Junko", :last_name=>"Collier", :username=>"Junko.Collier", :database_id=>"reilloC.oknuJ", :time_zone=>"Eastern Time (US & Canada)", :email=>"esta@mailinator.com", :network_name=>"Demo Network", :group_name=>nil, :user_id=>nil, :contact_id=>221682, :preferred=>false, :with_quiet_hour=>false, :quiet_time=>nil, :first_name_0=>"Junko", :last_name_0=>"Collier", :email_0=>"esta@mailinator.com"}, "testdec27@mailinator.com"=>{:first_name=>"Rodrick", :last_name=>"Reichel", :username=>"Rodrick.Reichel", :database_id=>"lehcieR.kcirdoR", :time_zone=>"Eastern Time (US & Canada)", :email=>"testdec27@mailinator.com", :network_name=>"Demo Network", :group_name=>nil, :user_id=>nil, :contact_id=>221684, :preferred=>false, :with_quiet_hour=>false, :quiet_time=>nil, :first_name_0=>"Rodrick", :last_name_0=>"Reichel", :email_0=>"dora@mailinator.com"}, "dora@mailinator.com"=>{:first_name=>"Rodrick", :last_name=>"Reichel", :username=>"Rodrick.Reichel", :database_id=>"lehcieR.kcirdoR", :time_zone=>"Eastern Time (US & Canada)", :email=>"dora@mailinator.com", :network_name=>"Demo Network", :group_name=>nil, :user_id=>nil, :contact_id=>221684, :preferred=>false, :with_quiet_hour=>false, :quiet_time=>nil, :first_name_0=>"Rodrick", :last_name_0=>"Reichel", :email_0=>"dora@mailinator.com"}}`

is there any way to use different variables with same email? I want to know is there a way to handle this?

**Comment by mgrishko** [comment]
@viveki2it 

Unfortunately, there is no way to implement this. 
Because according to the batch documentation: the key(email on which we are sending variables) must be unique, otherwise it must be replaced with the last value sent by this key.

[User Manual — Mailgun API  documentation ](https://documentation.mailgun.com/en/latest/user_manual.html#batch-sending-1)
