### ISSUE TITLE
NoMethodError (undefined method 'proxy_url' for Mailgun:Module)

### ISSUE THREAD

**Issue by Arshev** [mailgun/mailgun-ruby#273]
Hello mailgun-ruby team!
Installed version 1.2.7 on ruby on rails 7.0.4.2, ruby 3.2 getting error NoMethodError (undefined method 'proxy_url' for Mailgun:Module).
After rolling back to version 1.2.6 there is no error.
Trace:
`[c87617c2-49e9-413c-b980-2365e2e841f3] NoMethodError (undefined method 'proxy_url' for Mailgun:Module):
[c87617c2-49e9-413c-b980-2365e2e841f3]
[c87617c2-49e9-413c-b980-2365e2e841f3] mailgun-ruby (1.2.7) lib/mailgun/client.rb:19:in 'initialize'
[c87617c2-49e9-413c-b980-2365e2e841f3] mailgun-ruby (1.2.7) lib/railgun/mailer.rb:30:in 'new'
[c87617c2-49e9-413c-b980-2365e2e841f3] mailgun-ruby (1.2.7) lib/railgun/mailer.rb:30:in 'initialize'
[c87617c2-49e9-413c-b980-2365e2e841f3] mail (2.8.1) lib/mail/message.rb:278:in 'new'
[c87617c2-49e9-413c-b980-2365e2e841f3] mail (2.8.1) lib/mail/message.rb:278:in 'delivery_method'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionmailer (7.0.4.2) lib/action_mailer/delivery_methods.rb:65:in 'wrap_delivery_behavior'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionmailer (7.0.4.2) lib/action_mailer/delivery_methods.rb:79:in 'wrap_delivery_behavior!'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionmailer (7.0.4.2) lib/action_mailer/base.rb:870:in 'mail'
[c87617c2-49e9-413c-b980-2365e2e841f3] devise (4.8.1) lib/devise/mailers/helpers.rb:19:in 'devise_mail'
[c87617c2-49e9-413c-b980-2365e2e841f3] devise (4.8.1) app/mailers/devise/mailer.rb:9:in 'confirmation_instructions'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/abstract_controller/base.rb:215:in 'process_action'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/abstract_controller/callbacks.rb:234:in 'block in process_action'
[c87617c2-49e9-413c-b980-2365e2e841f3] activesupport (7.0.4.2) lib/active_support/callbacks.rb:118:in 'block in run_callbacks'
[c87617c2-49e9-413c-b980-2365e2e841f3] actiontext (7.0.4.2) lib/action_text/rendering.rb:20:in 'with_renderer'
[c87617c2-49e9-413c-b980-2365e2e841f3] actiontext (7.0.4.2) lib/action_text/engine.rb:69:in 'block (4 levels) in <class:Engine>'
[c87617c2-49e9-413c-b980-2365e2e841f3] activesupport (7.0.4.2) lib/active_support/callbacks.rb:127:in 'instance_exec'
[c87617c2-49e9-413c-b980-2365e2e841f3] activesupport (7.0.4.2) lib/active_support/callbacks.rb:127:in 'block in run_callbacks'
[c87617c2-49e9-413c-b980-2365e2e841f3] activesupport (7.0.4.2) lib/active_support/callbacks.rb:138:in 'run_callbacks'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/abstract_controller/callbacks.rb:233:in 'process_action'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/abstract_controller/base.rb:151:in 'process'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionmailer (7.0.4.2) lib/action_mailer/rescuable.rb:25:in 'block in process'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionmailer (7.0.4.2) lib/action_mailer/rescuable.rb:17:in 'handle_exceptions'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionmailer (7.0.4.2) lib/action_mailer/rescuable.rb:24:in 'process'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionview (7.0.4.2) lib/action_view/rendering.rb:39:in 'process'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionmailer (7.0.4.2) lib/action_mailer/base.rb:646:in 'block in process'
[c87617c2-49e9-413c-b980-2365e2e841f3] activesupport (7.0.4.2) lib/active_support/notifications.rb:206:in 'block in instrument'
[c87617c2-49e9-413c-b980-2365e2e841f3] activesupport (7.0.4.2) lib/active_support/notifications/instrumenter.rb:24:in 'instrument'
[c87617c2-49e9-413c-b980-2365e2e841f3] activesupport (7.0.4.2) lib/active_support/notifications.rb:206:in 'instrument'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionmailer (7.0.4.2) lib/action_mailer/base.rb:645:in 'process'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionmailer (7.0.4.2) lib/action_mailer/message_delivery.rb:128:in 'block in processed_mailer'
[c87617c2-49e9-413c-b980-2365e2e841f3] <internal:kernel>:90:in 'tap'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionmailer (7.0.4.2) lib/action_mailer/message_delivery.rb:127:in 'processed_mailer'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionmailer (7.0.4.2) lib/action_mailer/message_delivery.rb:118:in 'deliver_now'
[c87617c2-49e9-413c-b980-2365e2e841f3] devise (4.8.1) lib/devise/models/authenticatable.rb:204:in 'send_devise_notification'
[c87617c2-49e9-413c-b980-2365e2e841f3] devise (4.8.1) lib/devise/models/confirmable.rb:121:in 'send_confirmation_instructions'
[c87617c2-49e9-413c-b980-2365e2e841f3] devise (4.8.1) lib/devise/models/confirmable.rb:136:in 'block in resend_confirmation_instructions'
[c87617c2-49e9-413c-b980-2365e2e841f3] devise (4.8.1) lib/devise/models/confirmable.rb:239:in 'pending_any_confirmation'
[c87617c2-49e9-413c-b980-2365e2e841f3] devise (4.8.1) lib/devise/models/confirmable.rb:135:in 'resend_confirmation_instructions'
[c87617c2-49e9-413c-b980-2365e2e841f3] devise (4.8.1) lib/devise/models/confirmable.rb:342:in 'send_confirmation_instructions'
[c87617c2-49e9-413c-b980-2365e2e841f3] devise (4.8.1) app/controllers/devise/confirmations_controller.rb:11:in 'create'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_controller/metal/basic_implicit_render.rb:6:in 'send_action'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/abstract_controller/base.rb:215:in 'process_action'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_controller/metal/rendering.rb:53:in 'process_action'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/abstract_controller/callbacks.rb:234:in 'block in process_action'
[c87617c2-49e9-413c-b980-2365e2e841f3] activesupport (7.0.4.2) lib/active_support/callbacks.rb:118:in 'block in run_callbacks'
[c87617c2-49e9-413c-b980-2365e2e841f3] actiontext (7.0.4.2) lib/action_text/rendering.rb:20:in 'with_renderer'
[c87617c2-49e9-413c-b980-2365e2e841f3] actiontext (7.0.4.2) lib/action_text/engine.rb:69:in 'block (4 levels) in <class:Engine>'
[c87617c2-49e9-413c-b980-2365e2e841f3] activesupport (7.0.4.2) lib/active_support/callbacks.rb:127:in 'instance_exec'
[c87617c2-49e9-413c-b980-2365e2e841f3] activesupport (7.0.4.2) lib/active_support/callbacks.rb:127:in 'block in run_callbacks'
[c87617c2-49e9-413c-b980-2365e2e841f3] activesupport (7.0.4.2) lib/active_support/callbacks.rb:138:in 'run_callbacks'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/abstract_controller/callbacks.rb:233:in 'process_action'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_controller/metal/rescue.rb:22:in 'process_action'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_controller/metal/instrumentation.rb:67:in 'block in process_action'
[c87617c2-49e9-413c-b980-2365e2e841f3] activesupport (7.0.4.2) lib/active_support/notifications.rb:206:in 'block in instrument'
[c87617c2-49e9-413c-b980-2365e2e841f3] activesupport (7.0.4.2) lib/active_support/notifications/instrumenter.rb:24:in 'instrument'
[c87617c2-49e9-413c-b980-2365e2e841f3] activesupport (7.0.4.2) lib/active_support/notifications.rb:206:in 'instrument'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_controller/metal/instrumentation.rb:66:in 'process_action'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_controller/metal/params_wrapper.rb:259:in 'process_action'
[c87617c2-49e9-413c-b980-2365e2e841f3] activerecord (7.0.4.2) lib/active_record/railties/controller_runtime.rb:27:in 'process_action'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/abstract_controller/base.rb:151:in 'process'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionview (7.0.4.2) lib/action_view/rendering.rb:39:in 'process'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_controller/metal.rb:188:in 'dispatch'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_controller/metal.rb:251:in 'dispatch'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_dispatch/routing/route_set.rb:49:in 'dispatch'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_dispatch/routing/route_set.rb:32:in 'serve'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_dispatch/routing/mapper.rb:18:in 'block in <class:Constraints>'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_dispatch/routing/mapper.rb:48:in 'serve'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_dispatch/journey/router.rb:50:in 'block in serve'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_dispatch/journey/router.rb:32:in 'each'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_dispatch/journey/router.rb:32:in 'serve'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_dispatch/routing/route_set.rb:852:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] warden (1.2.9) lib/warden/manager.rb:36:in 'block in call'
[c87617c2-49e9-413c-b980-2365e2e841f3] warden (1.2.9) lib/warden/manager.rb:34:in 'catch'
[c87617c2-49e9-413c-b980-2365e2e841f3] warden (1.2.9) lib/warden/manager.rb:34:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] rack (2.2.6.2) lib/rack/tempfile_reaper.rb:15:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] rack (2.2.6.2) lib/rack/etag.rb:27:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] rack (2.2.6.2) lib/rack/conditional_get.rb:40:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] rack (2.2.6.2) lib/rack/head.rb:12:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_dispatch/http/permissions_policy.rb:38:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_dispatch/http/content_security_policy.rb:36:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] rack (2.2.6.2) lib/rack/session/abstract/id.rb:266:in 'context'
[c87617c2-49e9-413c-b980-2365e2e841f3] rack (2.2.6.2) lib/rack/session/abstract/id.rb:260:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_dispatch/middleware/cookies.rb:704:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_dispatch/middleware/callbacks.rb:27:in 'block in call'
[c87617c2-49e9-413c-b980-2365e2e841f3] activesupport (7.0.4.2) lib/active_support/callbacks.rb:99:in 'run_callbacks'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_dispatch/middleware/callbacks.rb:26:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_dispatch/middleware/debug_exceptions.rb:28:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_dispatch/middleware/show_exceptions.rb:26:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] railties (7.0.4.2) lib/rails/rack/logger.rb:40:in 'call_app'
[c87617c2-49e9-413c-b980-2365e2e841f3] railties (7.0.4.2) lib/rails/rack/logger.rb:25:in 'block in call'
[c87617c2-49e9-413c-b980-2365e2e841f3] activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:99:in 'block in tagged'
[c87617c2-49e9-413c-b980-2365e2e841f3] activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:37:in 'tagged'
[c87617c2-49e9-413c-b980-2365e2e841f3] activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:99:in 'tagged'
[c87617c2-49e9-413c-b980-2365e2e841f3] railties (7.0.4.2) lib/rails/rack/logger.rb:25:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_dispatch/middleware/remote_ip.rb:93:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_dispatch/middleware/request_id.rb:26:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] rack (2.2.6.2) lib/rack/method_override.rb:24:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] rack (2.2.6.2) lib/rack/runtime.rb:22:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_dispatch/middleware/executor.rb:14:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] rack (2.2.6.2) lib/rack/sendfile.rb:110:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_dispatch/middleware/ssl.rb:77:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] actionpack (7.0.4.2) lib/action_dispatch/middleware/host_authorization.rb:137:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] rack-cors (1.1.1) lib/rack/cors.rb:100:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] railties (7.0.4.2) lib/rails/engine.rb:530:in 'call'
[c87617c2-49e9-413c-b980-2365e2e841f3] /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in 'process_request'
[c87617c2-49e9-413c-b980-2365e2e841f3] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in 'accept_and_process_next_request'
[c87617c2-49e9-413c-b980-2365e2e841f3] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in 'main_loop'
[c87617c2-49e9-413c-b980-2365e2e841f3] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:419:in 'block (3 levels) in start_threads'
[c87617c2-49e9-413c-b980-2365e2e841f3] /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in 'block in create_thread_and_abort_on_exception'`

**Comment by pedrofs** [comment]
Same here. Production went crazy!

**Comment by Linuus** [comment]
Same with `Mailgun.api_host`. I opened a PR.
