### ISSUE TITLE
delete_if returning true from function when encountering a nil value

### ISSUE THREAD

**Issue by cheesecow** [mailgun/mailgun-ruby#294]
This will return true for the function [transform_for_mailgun](https://github.com/mailgun/mailgun-ruby/blob/master/lib/railgun/mailer.rb#L92)
https://github.com/mailgun/mailgun-ruby/blob/master/lib/railgun/mailer.rb#L148
which is not the intended behavior. The block needs to evaluate to true not be returned from.

```
def blah 
  [1,nil,3].delete_if do |a|
    return true if a.nil?
  end
  return 'not getting here'
end
blah
```

**Comment by nehresma** [comment]
Wow, nice catch.  This bug has been there for 5 years -- yikes!

**Comment by mgrishko** [comment]
Thanks for your accuracy
