### ISSUE TITLE
Error installing gem

### ISSUE THREAD

**Issue by JosephCastro** [mailgun/mailgun-ruby#30]
I get this, when I trying to install through gem install

```
Fetching: json-1.8.2.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing mailgun-ruby:
ERROR: Failed to build gem native extension.

    /usr/bin/ruby1.9.1 extconf.rb
/usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- mkmf         (LoadError)
    from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from extconf.rb:1:in `<main>'


Gem files will remain installed in /var/lib/gems/1.9.1/gems/json-1.8.2 for inspection.
```

**Comment by ShadySQL** [comment]
Same problem like me - any suggestions?

**Comment by JosephCastro** [comment]
I installing follow this: http://stackoverflow.com/questions/7645918/require-no-such-file-to-load-mkmf-loaderror

**Comment by nathanbrauer** [comment]
Same problem here.

**Comment by nathanbrauer** [comment]
Is there a way to make it so the `-dev` package isn't required?

**Comment by pirogoeth** [comment]
I believe this was fixed a while back - as far as I know, nobody is seeing this issue with newer versions. If I'm wrong, feel free to re-open this ticket :)
