### ISSUE TITLE
`set_delivery_time': wrong number of arguments (2 for 1)

### ISSUE THREAD

**Issue by nathanbrauer** [mailgun/mailgun-ruby#31]
The docs (`MessageBuilder.md` and `Messages.md`) say you're supposed to use this syntax: `mb_obj.set_delivery_time("tomorrow 8:00AM", "PST");`

But the actual def in `message_builder.rb` only includes one parameter: `def set_delivery_time(timestamp)` and the unit test only tests for one parameter as well.

(I'd issue a pull request, but I'm not familiar enough with Ruby to contribute confidently.)

**Comment by nathanbrauer** [comment]
See related files:
https://github.com/mailgun/mailgun-ruby/search?utf8=%E2%9C%93&q=set_delivery_time

**Comment by pirogoeth** [comment]
Looks like this was fixed a while back. Thanks for submitting an issue!
