### ISSUE TITLE
should be able to send nil like every other ruby library

### ISSUE THREAD

**Issue by jtoy** [mailgun/mailgun-ruby#32]
```
mail_params = {:to => params[:to],:bcc => params[:bcc],:from => params[:from],:text=> params['body'],:subject => params['subject']}
MAILGUN.send_message(domain,mail_params)
```

if params[:bcc] is  nil, the message wont send, the errror being:
Mailgun::CommunicationError: 400 Bad Request

  in ruby, sending nil usually means ignore/skip.

**Comment by pirogoeth** [comment]
@jtoy Are you still having this issue?

**Comment by pirogoeth** [comment]
So while the usual convention in Ruby is for nil to be ignored in parameters, that is not the case here. Instead of getting a `400 Bad Request` back, which is quite ambiguous, send_message will now raise a `ParameterError` and dump the hash, allowing you to see which was set of values are nil.
