### ISSUE TITLE
Remove `OpenStruct` usage, will warn in Ruby 3.4, raise in Ruby 3.5

### ISSUE THREAD

**Issue by Earlopain** [mailgun/mailgun-ruby#321]
Ruby 3.4 will issue a warning for this, and Ruby 3.5 will raise. Also see https://bugs.ruby-lang.org/issues/20309, https://github.com/ruby/ruby/pull/10428

There is a single place here that will need adjusting: https://github.com/mailgun/mailgun-ruby/blob/1a2d2dcf253c2265267d261595416daa879a6342/lib/mailgun/response.rb#L15-L19

The other places are test only and can be fixed simply by adding it to the Gemfile (or alternativly just return a hash from `response_generator` and use the `from_hash` method, seems like that should work). I suggest replacing the one usage with the following (untested, should be fine):

```rb
ResponseHash = Struct.new(:body, :code)

def self.from_hash(h)
  # Create a "fake" response object with the data passed from h
  self.new ResponseHash.new(h[:body] , h[:code])
end
```

**Comment by frederikspang** [comment]
Furthermore, OpenStruct usage is generally discouraged, due to invalidating the global method cache in Ruby.

From [RuboCop documentation](https://www.rubydoc.info/gems/rubocop/0.61.1/RuboCop/Cop/Performance/OpenStruct):
> Instantiation of an `OpenStruct` invalidates Ruby global method cache as it causes dynamic method definition during program runtime.
