### ISSUE TITLE
Sending raw MIME does not work

### ISSUE THREAD

**Issue by clhammer** [mailgun/mailgun-ruby#42]
When specifying the :message parameter it should write the string passed in this parameter to a file then submit that temp file to the messages.mime endpoint. 

https://github.com/mailgun/mailgun-ruby/blob/1cb8b87a68a2d82db544bde7af388a61e3e70059/lib/mailgun.rb#L42-L58

Most of this works correctly, however no matter what you pass in the :message parameter it is not converted to the file correctly, the file is always empty.

This can be replicated using the custom MIME example found on:

https://github.com/mailgun/mailgun-ruby/blob/1cb8b87a68a2d82db544bde7af388a61e3e70059/Snippets.md

**Comment by Easy-D** [comment]
I think a ```file.rewind```after the write (https://github.com/mailgun/mailgun-ruby/blob/1cb8b87a68a2d82db544bde7af388a61e3e70059/lib/mailgun.rb#L139) will fix this.

**Comment by pirogoeth** [comment]
Looks like this was fixed in #43, but this issue also uncovered an issue with the snippet docs. All is good now. :)
