### ISSUE TITLE
POST to "lists" returns 400 Bad Request

### ISSUE THREAD

**Issue by Mileshosky** [mailgun/mailgun-ruby#44]
https://github.com/mailgun/mailgun-ruby/blob/1cb8b87a68a2d82db544bde7af388a61e3e70059/spec/integration/mailgun_spec.rb#L470-L473

While trying to make a POST to lists, I receive a 400 Bad Request error.  I have tried running the above code straight from your spec and it fails as well.  I have other code that is making successful POST requests using the same API key as what is being used to create a list.

**Comment by Mileshosky** [comment]
The issue was creating a new list for an invalid domain.  Having server response messages bubble up would be an excellent user experience.

**Not useful**
`Mailgun::CommunicationError: 400 Bad Request`


**Useful**
`Mailgun::CommunicationError: 400 Bad Request:  Invalid domain some.domain.tld`

**Comment by jturmel** [comment]
:+1:

**Comment by pirogoeth** [comment]
This ties back to #61 which I will be trying to resolve today -- should hopefully have a patch out soon.

**Comment by pirogoeth** [comment]
@Mileshosky This PR should be a bit more informative for errors - https://github.com/mailgun/mailgun-ruby/pull/65

Does that work for you?
