### ISSUE TITLE
Reply to does not work using message builder

### ISSUE THREAD

**Issue by hirowatari** [mailgun/mailgun-ruby#45]
```
message_builder = Mailgun::MessageBuilder.new
message_builder.add_recipient('h:reply-to', 'test@example.com')
```

should set the reply to.  That doesn't work, nor does:
`message_builder.add_custom_parameter('h:reply-to', 'test@example.com')
`
The issue here, is if an array of reply-to addresses is posted, then the reply to address does not get set (or at least does not seem to be in gmail).
I'd suggest that either:
(1) Complex_setter and simple_setter should not create arrays of size one.
(2) The MailGun backend that receives these parameters should treat these the same.

Presently there is no good way to set the reply to address.  I've resorted to using: 
`message_builder.message['h:Reply-To'] = 'test@example.com'` which feels like a bit of hack.

I would create a PR for (1) if you like.

**Comment by PabloVallejo** [comment]
👍

**Comment by pirogoeth** [comment]
I've got a solution for this in #68 - feel free to comment on my changes.
