### ISSUE TITLE
Might be wise to mark this as abandoned

### ISSUE THREAD

**Issue by hirowatari** [mailgun/mailgun-ruby#46]
Given that this hasn't been updated in a year, isn't updated to the v3 API, and the maintainers aren't replying to PRs or issues, I think it would be wise to not give users the idea that this is being maintained.

Please correct me if this is being maintained in some capacity.

**Comment by sixfeetover** [comment]
I'm trying to keep this moving forward over at [veracross/mailgun-ruby](https://github.com/veracross/mailgun-ruby), where my various PRs are merged (including using v3). I will also accept other PRs into my branch.

**Comment by baburdick** [comment]
@sixfeetover: Where are you releasing gems for your fork? I don't see them on rubygems.org. Suggestion: call it veracross-mailgun-ruby.

**Comment by sixfeetover** [comment]
I could do that. I haven't needed to so far as there have only been a few commits and I've just bundled it right from GitHub.

**Comment by gimpporbust** [comment]
It looks like @dan-ding has a PR #49 that helps tackle some of the issues and unaddressed PRs. Maybe we can use that as a starting point to get this kickstarted again. I think #49 needs review, and at least broken up to address each fix separately. I'm not sure how I feel about having a commit message saying we bumped to api v3 (a 2-3 line fix) and in reality it hides many updates and not to mention commit snipes a lot of people from the PRs they've added here.

I don't know anything about passing the torch on GH for a project, but how could we get mailgun to give ownership to another party?

**Comment by jrodom** [comment]
All, 
I apologize that we haven't done a good job stewarding this, we're going to get dan's changes merged and will be doing a better job getting things moved through the process.  

Josh

**Comment by baburdick** [comment]
Glad to hear, @jrodom. It's always best when the vendor can manage their own public API modules. Looking forward to seeing mailgun-ruby active and progressing.

**Comment by CGA1123** [comment]
Is it in mailgun's plan to start maintaining this again?

If not, I think it would be at least sensible to remove the ruby part of the documentation, given that this library is no longer actively maintained, and the `rest-client` dependency is outdated.

**Comment by Fustrate** [comment]
March 7th:

> I apologize that we haven't done a good job stewarding this, we're going to get dan's changes merged and will be doing a better job getting things moved through the process.

and no commits in the 7 months since.

Trying to find anyone active on Github who might be able to help: @horkhe @thrawn01

**Comment by rossmeissl** [comment]
Here's what Mailgun has to say:

> We've recently onboarded an engineer to our team that will be updating and maintaining our SDKs. They'll be receiving some attention and care. :) 
> 
> Thanks,
> Nolan
> @Mailgun

**Comment by jrodom** [comment]
We have someone working on this now @pirogoeth.  All open PRs have been merged or closed and @pirogoeth is working through all open issues.  We appreciate your patience with us on this!
