### ISSUE TITLE
Problem with generate_hash Method in OptInHandler

### ISSUE THREAD

**Issue by cpietsch82** [mailgun/mailgun-ruby#47]
Hi there,

i'm using the Opt-In Handler Method for the mailgun gem. My problem is, that the generated hash is too long, so i have problems to call the url in a mail from a web mail portal like www.web.de. Is there a possibility to manipulate the hash for the Opt In Validation ?

Best regards,
Christian

**Comment by pirogoeth** [comment]
@cpietsch82 Are you still having this issue?

**Comment by cpietsch82** [comment]
hi @pirogoeth , sorry for my late response. 
Everything is fine now! Thanks

**Comment by pirogoeth** [comment]
@cpietsch82 No worries! Thanks for the response!
