### ISSUE TITLE
Getting started with rails isn't easy

### ISSUE THREAD

**Issue by atinder** [mailgun/mailgun-ruby#52]
I have tried 2 gems for mailgun. Because this one is official so I tried it first and no success delivering emails.
Then I tried https://github.com/jorgemanrubia/mailgun_rails success with 10 seconds.

Maybe docs need some update or its not that good with rails. ( Just my 2 cents )

**Comment by dan-ding** [comment]
Can you provide more details to the issue?

**Comment by atinder90** [comment]
Tried this in my Gemfile
`gem 'mailgun-ruby', '~>1.0.5', require: 'mailgun'`
It didn't installed, tried following
`gem 'mailgun-ruby', '~>1.0.2', require: 'mailgun'`
It installed.

```
Mailgun.configure do |config|
  config.api_key = 'your-secret-key'
end
```
there are two api keys(private/public) in mailgun account, i **guess** above refers to the private key.

After this I can see ActionMailer is sending emails in the server logs but niether they are delivered nor I can see them in mailgun account logs.

Does it work with ActionMailer for rails or we need to use `Mailgun::Client.new("your-api-key")` every time we send emails ?

**Comment by lukebooth** [comment]
For `gem 'mailgun-ruby', '~>1.0.5', require: 'mailgun'` part of your troubles, that was a mistake. There actually isn't a version `1.0.5` (see #51).

I think the term "secret-key" implies your private key, but if that isn't clear, maybe we can modify the readme.

After adding _this_ gem, you'll actually be using the gem to send messages, not `ActionMailer`. With `mailgun_rails` gem, you set mailgun as the delivery handler for `ActionMailer`. `mailgun-ruby` is just to help you access Mailgun with plain ol' ruby and isn't intended to be an Rails plugin (but totally can be).

To use it in Rails a good setup would be to have a config file with your keys and an initializer to access those. Like [this gist](https://gist.github.com/lukebooth/da278a74926333be50e9), that way you're not putting your secrets in your code.

**Comment by pirogoeth** [comment]
@atinder Are you still having this issue?

**Comment by atinder** [comment]
yes, actually I was looking for more of Rails friendly gem. mailgun_rails seems to be solving my problem.

**Comment by pirogoeth** [comment]
Alright, glad you found something that works for you! I'll try to make this library more Rails friendly. Thanks for the comments!

**Comment by pirogoeth** [comment]
Going to use #14 in place of this issue.
