### ISSUE TITLE
Error informativeness is abysmal

### ISSUE THREAD

**Issue by emirkin** [mailgun/mailgun-ruby#61]
Could you please make errors more informative?

On multiple occasions (with different reasons), I got:

```
Mailgun::CommunicationError: undefined method `each_byte' for nil:NilClass
    from /Users/zzz/.rvm/gems/ruby-2.2.3/bundler/gems/mailgun-ruby-cae112741ae8/lib/mailgun/client.rb:58:in `rescue in post'
    from /Users/zzz/.rvm/gems/ruby-2.2.3/bundler/gems/mailgun-ruby-cae112741ae8/lib/mailgun/client.rb:55:in `post'
    from /Users/zzz/.rvm/gems/ruby-2.2.3/bundler/gems/mailgun-ruby-cae112741ae8/lib/mailgun/client.rb:39:in `send_message'
```

This communication error is absolutely uninformative and there is nothing I can do with it except prying deep inside `rest-client` for possible clues.

**Comment by pirogoeth** [comment]
@emirkin Sorry for the wait -- what does your code where you're calling `send_message` look like?

**Comment by pirogoeth** [comment]
I will be working on this today -- should hopefully have a fix out soon :)

**Comment by pirogoeth** [comment]
@emirkin Can you let me know if this patch works a little better for you? https://github.com/mailgun/mailgun-ruby/pull/65
