### ISSUE TITLE
MessageBuilder custom parameter adds spurious [ ]

### ISSUE THREAD

**Issue by Fjan** [mailgun/mailgun-ruby#77]
Adding a custom parameter according to the docs:
```mb_obj.add_custom_parameter('h:List-Unsubscribe',"<mailto:unsubscribe@mydomain.com>")```

Results in this header in the email:
```List-Unsubscribe[]: <mailto:unsubscribe@mydomain.com>```

The added [ ] appears with any custom header and any contents, so that would seem to be a bug.

**Comment by pirogoeth** [comment]
@Fjan Thank you for the report! I will look in to this asap :)

**Comment by pirogoeth** [comment]
@Fjan Could you pull the code from #78 and check that it fixes your issue? Also, now you should be able to use `mb_obj.header 'List-Unsubscribe', '<mailto:unsubscribe@mydomain.com>'` instead of `add_custom_parameter`.

**Comment by Fjan** [comment]
Thanks @pirogoeth, but I was pressed for time so I rewrote my script to use the SMTP interface and did it that way, it's going to be a little while before I need to send out another newsletter.

**Comment by pirogoeth** [comment]
@Fjan Sorry about that! I've done testing from my end and everything looks okay so I'm gonna close this issue, but feel free to re-open this issue if you still have problems with it!

**Comment by Fjan** [comment]
@pirogoeth I finally had some time to try out the fix and I can confirm the 'List-Unsubscribe' header now works correctly, thanks!

**Comment by pirogoeth** [comment]
@Fjan Awesome, thanks!
