### ISSUE TITLE
Implement Railgun as a Railtie

### ISSUE THREAD

**Issue by timdorr** [mailgun/mailgun-ruby#80]
Thanks for adding the railgun stuff in the last version! Makes my life a lot easier.

One thing I missed initially was the need to include a `require 'railgun'` at the top of my production.rb. That's because the railgun stuff doesn't autoload, which makes sense in the case of a non-Rails project. 

You could simply add a `require 'railgun' if defined?(Rails)` to your mailgun-ruby.rb file and call it a day. But what would be more semantic for Rails would be to implement [a Railtie](http://api.rubyonrails.org/classes/Rails/Railtie.html). For now, it would be to simply [move this line](https://github.com/mailgun/mailgun-ruby/blob/e3162de74da69f758bca08f51899eb41063291dd/lib/railgun/mailer.rb#L162) out of the global context and into an `initializer` method instead. But there could be other things that could be added down the line.

I'm more than happy to work up a PR. Just wanted to write this down as an issue first before I forget :smile:

**Comment by pirogoeth** [comment]
@timdorr Thanks! I will look in to this tomorrow :) feel free to work up a PR, if you'd like!
