### ISSUE TITLE
Attachments are ignoring filename when sent using ActionMailer

### ISSUE THREAD

**Issue by rmcsharry** [mailgun/mailgun-ruby#82]
I have Rails 5.0.1 using ActionMailer code as follows:

```ruby

  def pdf_quote(proposal)
    @proposal = proposal
    email_with_name = %("#{@proposal.first_name} #{@proposal.last_name}" <#{@proposal.email}>)
    @filename = "QD-#{@proposal.qd_number}_#{@proposal.last_name}.pdf"
    attachments[@filename] = {
      mime_type: 'application/pdf',
      encoding: 'Base64',
      content: @proposal.pdf_base64
    }  
    mail(
      to: email_with_name,
      from: 'Floorbook UK <email address>',
      subject: 'Your Personal Flooring Quote is attached',
      sent_on: Time.now
      )    
  end
```

I have tried by hardcoding 'test.pdf' also. I have tried replace flilename: with remoteName inside the hash (as I see th PHP plugin uses remoteName).

No matter what I try the filename does not appear in the JSON in the mailgun logs.

I can however see it in the Rails log. For example, here is the log when I tried using remotename:

```
----==_mimepart_58acb0bbc5906_b35a3ff9c303fa14374b
Content-Type: application/pdf
Content-Transfer-Encoding: quoted-printable
Content-Disposition: attachment;
 filename=QD-1002_McSharry.pdf
remotename: QD-1002_McSharry.pdf
Content-ID: <58acb0bbc8aaf_b35a3ff9c303fa14376d9@Richards-MacBook-Air.local.mail>

%PDF-1.3
```

Here is the relevant part of the JSON from the mailgun log:

"message": {
    "headers": {
      "to": "Richard McSharry <my email>",
      "message-id": "20170221213251.124698.55612.AAE859F0@sandbox4d05645e78ac4c81b7b542d27c5e87ad.mailgun.org",
      "from": "Floorbook UK <my email>",
      "subject": "Your Personal Flooring Quote is attached"
    },
    "attachments": [
      {
        "filename": "",
        "content-type": "application/pdf",
        "size": 9004
      }
    ],
    "recipients": [
      "my email"
    ],
    "size": 11517
  },

**Comment by pirogoeth** [comment]
@rmcsharry I'm assuming this is with the new Railgun code / version 1.1.4 of the gem?

**Comment by rmcsharry** [comment]
Yes - mailgun-ruby (1.1.4)

**Comment by pirogoeth** [comment]
@rmcsharry I will look in to this, it very well could be an issue with Railgun. I'll let you know what I find :)

**Comment by pirogoeth** [comment]
@rmcsharry I think I found the issue. Stand by for a PR.

**Comment by rmcsharry** [comment]
@pirogoeth Awesome, thanks for the quick fix. I just tested it and it works! :)

**Comment by pirogoeth** [comment]
@rmcsharry Awesome! I'll cut an official release on Monday :)

**Comment by rmcsharry** [comment]
@pirogoeth This branch I tested was labelled as version 1.1.5. But now that you have merged it, the version of master branch did not change, it is still 1.1.4 - was that the intention?

**Comment by pirogoeth** [comment]
@rmcsharry It seems that 1.1.5 has been released to Rubygems and 1.1.5 is in master (tagged as v1.1.5)..

**Comment by rmcsharry** [comment]
Ok thanks I just removed it from my project and bundle installed again, now it shows up as 1.1.5. Thanks for confirming!

**Comment by pirogoeth** [comment]
Of course!

**Comment by pavanscs** [comment]
new issues can any one please help me with this i want a attachment file that was send to the mailer has to be open in a new tab
