### ISSUE TITLE
Mailgun::Suppressions

### ISSUE THREAD

**Issue by rgraff** [mailgun/mailgun-ruby#85]
Is there any reason 'mailgun/suppressions' is not loaded? I noticed there's also no docs for it but the code exists and works if I require it in myself.

**Comment by pirogoeth** [comment]
@rgraff Sorry about that, haven't gotten around to writing the docs yet! I'll make sure to get that out in a few days. I'll also add a method somewhere to return a prepared Suppressions instance.

**Comment by pirogoeth** [comment]
Hey @rgraff, sorry it has taken a bit - you mind looking at the docs and suppressions changes I added in #98 to see if that is sufficient? Thanks!

**Comment by pirogoeth** [comment]
This should be fixed up in #98. Feel free to re-open if the release did not fix it.
