### ISSUE TITLE
Mailgun::Error (Too many recipients, max is 1000):

### ISSUE THREAD

**Issue by bbnnt** [mailgun/mailgun-ruby#87]
Hello;

i'm completely stuck with the following  error `Mailgun::Error (Too many recipients, max is 1000)`

I'm using the following piece of code to deliver email in batch :

```
recipients.in_groups_of(500) do |group|
hash = {}
group.compact.each do |r|
  hash["#{r["email"]}"] = {name: "#{r["firstname"]}", id: r.id }
end
to = recipients.collect{ |r| r.email }.join(",")
parameters[:to] = to
parameters[:'recipient-variables'] = hash.to_json
Mailgun().messages.send_email(parameters)
end
```

(i might be missing some pieces but it was working before correctly — before we reached 1000 total recipients). Parameters contains an array of email adresses, which has been limited to 500. I don't get why I till get this error

Thanks if anyone has clues about it

Best regards

**Comment by adamof** [comment]
@bbnnt what was the problem?
