### ISSUE TITLE
Better documentation wanted

### ISSUE THREAD

**Issue by Lubmes** [mailgun/mailgun-ruby#89]
How would one go about using a txt.erb template file for building up a message dynamically?
Attachments in the message_params hash? 

Why not a proper list or readme for all these things? Most certainly the basics. Now the only thing online that adds some clarification is a message on mailgun's blog from 2014 and a very short readme?!
I got stuff working somewhat, but I thought the goal of an API should be to make things simpler.

**Comment by lukebooth** [comment]
I think typically if you can't find what you're looking for in the README, then programmers will go into the code to find their answers. This is open source anyway, so you can see everything and how it works. Specifically look in the tests, there are a lot of them for this gem and you can probably find all the examples you need there.

[Example of building a message not from parameters](https://github.com/mailgun/mailgun-ruby/blob/master/spec/integration/mailgun_spec.rb#L79)
👆 Maybe that helps you understand how the breakdown of building a message works.

[Adding an attachment](https://github.com/mailgun/mailgun-ruby/blob/master/spec/unit/messages/message_builder_spec.rb#L209)
👆 With the knowledge from the first example, use this method to add attachments.

If you're just using Ruby [APIdoc](https://apidock.com/ruby/ERB) has a good erb example (about half way down the page) called _Plain Text_

**Comment by rsov** [comment]
Few lines of tutorial how to send html emails would be appreciated. (From stand alone gem, not rails plugins)

**Comment by pirogoeth** [comment]
@rsov @Lubmes does this document help? https://github.com/mailgun/mailgun-ruby/blob/master/docs/Messages.md

For some reason it was not linking in the README, but I will make sure it gets in there now.

**Comment by Lubmes** [comment]
Yes a lot. Otherwise there was too much ambiguity between the message params hash and message builder. 

Reason why I ask this is because on this blog post http://blog.mailgun.com/the-official-mailgun-ruby-sdk-is-here/ there is a reference to a "list on GitHub" that gives a '404'. 

Simply makes things easier: to find the doc you know must be there.

**Comment by pirogoeth** [comment]
I have updated the README with a link to that document and fixed the links on the blog post. Thank you!
