### ISSUE TITLE
Mailgun::BatchMessage doesnt replace the placeholders with recipient data.

### ISSUE THREAD

**Issue by rsov** [mailgun/mailgun-ruby#90]
The `Mailgun::BatchMessage` doesn't replace the placeholders in the email.

I'm trying to construct the batch message from a csv file
It works with `"%recipient.account_id%"` but not with `"%account_id%"`, even thought the documentation states that it should

``` ruby
batch = Mailgun::BatchMessage.new(Mailgun::Client.new, Mailgun.domain)
# pretend that from and subject are set
batch.body_html("<p>%account_id%</p>")

csv_data.each do |d|
  batch.add_recipient(:to, d[:email], d.to_h)   
end

puts batch.recipient_variables
batch.finalize
```

Csv data example:
```ruby
d = {
  email: "test@test.test",
  account_id: 123
}
```

The `recipient_variables` puts out correct info, however i can't seem to find it in the log and the `"%account_id%"` doesn't get replaced
```ruby
{
   "test@test.test" => {
      email:  "test@test.test",
      account_id: 123
  }
}
```

Looks like the same as in #22 

Relevant documentation:
http://blog.mailgun.com/the-official-mailgun-ruby-sdk-is-here/
https://github.com/mailgun/mailgun-ruby/blob/master/docs/Messages.md#usage---batch-message

**Comment by pirogoeth** [comment]
@rsov Sorry about that, the documentation in this repo needs to be updated. The correct way to reference recipient variables is with `%recipient.yourvar%`. You can read more in the official [Batch Sending](https://documentation.mailgun.com/user_manual.html#batch-sending) documentation.
