### ISSUE TITLE
options[:reply_to] in Rails 5's Actionmailer::Base's message object doesn't get transformed

### ISSUE THREAD

**Issue by xinspire** [mailgun/mailgun-ruby#92]
I'm running Rails 5.0.2, and passing `options[:reply_to]` to `Actionmailer::Base.mail` generates a message object with a Reply-To header, but it doesn't actually get delivered with the reply-to header by mailgun-ruby.

I had to add
`mb.reply_to(mail[:reply_to].to_s) if mail[:reply_to].present?`
inside `build_message_object` in `Railgun::Mailer` to get it to work.

**Comment by pirogoeth** [comment]
This should be fixed up in #98. Feel free to re-open if the release did not fix it.
