### ISSUE TITLE
(slightly dumb question) Why adapters?

### ISSUE THREAD

**Issue by ghost** [mailgun/mailgun-ruby#95]
Hello,
I am configuring my app to work with MailGun, which is awesome.
Without even thinking, I quickly googled for a `mailgun` gem, quickly installed it and everything worked straight away. I could send confirmation emails and receive them in my inbox.

I then tried without a gem (or adapter) and it worked pretty much the same way (the email went straight to the trash, actually. Not sure why) so I am wondering. Why the need for an adapter? Should I re-install the adapter gem and do it that way instead?

My code literally changed from:
```

  config.action_mailer.delivery_method = :mailgun

  config.action_mailer.smtp_settings = {
    :api_key           => ENV['MAILGUN_API_KEY'],
    :domain           => ENV['MAILGUN_DOMAIN']
  }

```
to: (without the extra `gem` dependency!)
```

  config.action_mailer.delivery_method = :smtp

  config.action_mailer.smtp_settings = {
    :port           => ENV['MAILGUN_SMTP_PORT'],
    :address        => ENV['MAILGUN_SMTP_SERVER'],
    :user_name      => ENV['MAILGUN_SMTP_LOGIN'],
    :password       => ENV['MAILGUN_SMTP_PASSWORD'],
    :domain         => ENV['MAILGUN_DOMAIN'],
    :authentication => :plain,
  }

```

**Comment by pirogoeth** [comment]
@ClaudioCarmeli realistically, both ways should work fine, but using the API adapter, you can also create various suppressions (unsubscribes, complaints, bounces) from your app and take advantage of the advanced features the Mailgun API provides.
